### ISSUE TITLE
Steam installed but "No supported game libraries detected!"

### ISSUE THREAD

**Issue by stringfieldmark** [terrymacdonald/DisplayMagician#5] opened 2021-04-05 12:44 UTC
**Describe the bug**
When on the "4. Choose Game to start" tab there are no games detected (see attached image)

Steam is installed in the default location of "C:\Program Files (x86)\Steam". I have five games installed and are all in the default "C:\Program Files (x86)\Steam\steamapps\common" folder.

I understand you look in the "Computer\HKEY_**LOCAL_MACHINE**" registry key location, however, all my game ID's are in the "Computer\HKEY_**CURRENT_USER**" registry key location. Specifically in the "Computer\HKEY_**CURRENT_USER**\SOFTWARE\Valve\Steam\Apps" registry key location.

I suspect this is the reason why I cannot see any games under the "4. Choose Game to start" tab.

**To Reproduce**
_Possibly not applicable_

**Expected behaviour**
For the program to detect my installed Steam games

**Screenshots**
_**Application tab image:**_
![(DisplayMagician)_4 -Choose-Game-to-start_Tab](https://user-images.githubusercontent.com/29753726/113574625-6270bd00-9614-11eb-9c60-69c4432d9687.png)

**Registry images:**
_**(DisplayMagician)_LocalMachine_SteamPath.png**_
![(DisplayMagician)_LocalMachine_SteamPath](https://user-images.githubusercontent.com/29753726/113574741-9c41c380-9614-11eb-915e-ae914f4da168.png)

_**(DisplayMagician)_LocalMachine_AppID.png**_
![(DisplayMagician)_LocalMachine_AppID](https://user-images.githubusercontent.com/29753726/113574766-a499fe80-9614-11eb-9113-2dd18a9de53a.png)

_**(DisplayMagician)_CurrentUser_SteamPath.png**_
![(DisplayMagician)_CurrentUser_SteamPath](https://user-images.githubusercontent.com/29753726/113574776-ad8ad000-9614-11eb-8cff-041f05f20bd1.png)

_**(DisplayMagician)_CurrentUser_AppID.png**_
![(DisplayMagician)_CurrentUser_AppID](https://user-images.githubusercontent.com/29753726/113574782-b11e5700-9614-11eb-8589-e3bb0af1ec14.png)

**Reporting Logs**
_Possibly not applicable_

**Enviroment (please complete the following information):**
 - Windows Version: Windows 10 (20H2 (OS Build 19042.906)
 - Steam Built: Mar 23 2021, at 13:13:13
 - Steam API: v020
 - Steam package version: 1616532526

**Additional context**
_Not applicable_

If there is any further info you require, please do let me know.

**Comment by terrymacdonald** [comment] 2021-04-07 10:43
Thanks for the bug report! I really appreciate you helping find these issues. 

I'm looking into this at the moment, as I have a couple of other test machines at my disposal now. The registry screenshots help a lot. I'm working on the issue and will report back when I've done some more investigating.

**Comment by terrymacdonald** [comment] 2021-04-09 02:33
So, I've been doing some research on this over the last few days. It seems like the problem is two-fold:

- Steam appears to have changed the way they use their config vdf file
- I tried using a different registry key to the one used before that mucks up some of the logic I had built previously.

The upshot is that I'm now developing a new fix, but it involves reverse engineering the changes Steam made. This may take a few days more to fix. Sorry!

**Comment by stringfieldmark** [comment] 2021-04-09 06:56
Hi,

Absolutely no apology needed. Just glad to help.

When the bugs are all ironed out, this will be the best display changer out
there. It has a great interface and some really nice features.

I have noted down some other bugs and will be happy to relay them to you.
Would you like them sent through individually or in one shot? I'm happy to
send them through however you'd like them. I know some developers like them
in one shot to check for any similarities, but some like to work on one at
a time before moving onto the next.

Let me know. I'm more than happy to do any testing you may need.

Regards,

Mark

**Comment by terrymacdonald** [comment] 2021-04-09 07:07
Hi Mark,

One issue at a time would be great, because I'll be able to make sure I
properly track and test each one.

Thanks for the kind words too!

Be sure to log any ideas you have for enhancements . I've added everything
I can think of, and everything that I wanted in a display manager, but
always happy to hear of any improvements I can make.

Thanks
Terry

**Comment by stringfieldmark** [comment] 2021-04-09 07:13
Will do and will do.

**Comment by terrymacdonald** [comment] 2021-04-09 21:18
I think I got this one sorted now. It was all based on my understanding of how Steam config.vdf worked. I thought that config.vdf stored all it's steam library folders within that file. So I was only searching for libraries listed in that file.

Further testing showed that the config.vdf only shows the **additional** steam library folders, so I should have been searching the default steam library folder within the Steam base folder location as well.  What this meant was that people with their steam games in the default steam installation location wouldn't have their games show up :(. This has now been fixed in develop branch and will be released in v1.0.4.

This didn't show up in my testing because I had installed all my Steam games in additional steam libraries rather than the default one. I have now installed one of my games in the default location just to ensure my testing covers this situation in the future.

I have also fixed up which steam registry locations are inspected to make them work better, and I have also found a way to filter out the steam games from the list of steam apps so that I show the right ones.

IMPORTANT NOTE: After you upgrade to v1.0.4 you will need to edit each shortcut and reselect your game. We had previously incorrectly been choosing the wrong Steam AppID for the games, having chosen the last DLC content ID rather than the game itself. This logic is now fixed, but you'll need to re-chose the game to set it to the right AppID. Apologies for the inconvenience!

**Comment by stringfieldmark** [comment] 2021-04-09 22:34
Awesome, thanks for the update!

I'll install and test I'll feed back. Once this has been nailed down, I'll
send through the next bug 😀

**Comment by terrymacdonald** [comment] 2021-04-10 03:49
Just to confirm that the fix will be in 1.0.4, which I'm still fixing some
audio bugs I've found. So it will probably be tomorrow before it's released.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-04-10 10:47
@stringfieldmark I've released v1.0.4, and hopefully it corrects all the issues you're experiencing. To update, just start DisplayMagician, and it will detect there is an update, and will update for you. No need to do it manually.

Hopefully I've also pre-emptively fixed some of the other issues you mentioned above, but if not please log a new issue per bug and I'll get onto fixing them for v1.0.5 :).

And thank you for using DisplayMagician!

I'm going to close this issue for now, but I'll reopen it if you still have problems.

**Closed by terrymacdonald** 2021-04-10 10:47 UTC
Labels: bug, good first issue

**Comment by stringfieldmark** [comment] 2021-04-19 12:40
Apologies for taking so long to report back on this.
V1.0.4 has solved this problem so a massive thanks for sorting this one out.
This software is exactly what I have been looking for and makes switching displays a pleasure.

Well done and keep up the great work

**Comment by DragRedSim** [comment] 2021-09-04 10:39
Oddly enough, my install of Steam does not store the extra libraries location in SteamPath\config\config.vdf at all, but rather in SteamPath\steamapps\libraryfolders.vdf. I've created a fork with a duplicated logic flow to cover that file as well, and will send through a PR to analyse.
