### ISSUE TITLE
Changes Display Scale and Layout

### ISSUE THREAD

**Issue by throbbie** [terrymacdonald/DisplayMagician#292] opened 2024-02-15 02:51 UTC
I only use one Nvidia Surrpund setup that doesn't change. I toggle it on first thing when I use my computer and leave it on. I use a hot key and it works great. The program is really simple to use, so thankyou for your time.

I have one problem: when I use the jockey to change to the profile it changes the Scale and Layout setting on Windows 10. So all of my programs and task bar are massive. I then have to change it. I wrote a script that uses a hotkey to lower this setting but I have to do it multiple times. Any idea why this is happening and how to stop it?

Also, is there a way to automatically use that display on startup?

Thanks in advance! Keep up the great work.

**Comment by terrymacdonald** [comment] 2024-02-18 08:31
Hi @throbbie,

I'm not sure that is something that I can sort out. It might be something to do with either the Windows Display Settings or the NVIDIA Control Panel settings stored within the Display Profile. 

Before we do any more troubleshooting, can you first download this test version of DisplayMagician, then install it? Then please check if you still have the same issue. This new test version has had a LOT of changes in the video libraries which make it more reliable, and your test will highlight if this was a bug I already fixed.

[DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip](https://github.com/terrymacdonald/DisplayMagician/files/14249946/DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip)

If you still are having the same issue even after you've installed v2.6.0.522, then then next step to try is to update your Display Profile. Updating a Display Profile is a new feature in the next release of DisplayMagician, and it allows you to 'refresh' your Display Profile if something stops working. This feature was added to make it simpler in situations like this.

To update your Display Profile, please set up your display layout exactly the way you want it to be, and then open up DisplayMagician, go to Display Profiles, and select the Display Profile you want to update. Click on 'Update' and then answer 'Yes' when if asks you to confirm. Your Display Profile config should be overwritten with the one you're using now.

Next try swapping to another Display Profile. and then back again, and see if the problem has now been fixed. If it is fixed, please come back here and say it is fixed, and then close this Github issue.

If the problem is still occurring, then please do this:
- Go to the Settings window
- Click 'Create Support ZIP File' button
- Save the ZIP file to your computer
- Upload the Support ZIP File to this Github issue through your web browser

I really hope the latest test version will fix your issues, but if it doesn't the Support ZIP File should give me some more information to work with.
 
Thanks
Terry

**Comment by terrymacdonald** [comment] 2024-02-18 08:33
@throbbie Actually this is a later version so please use this version instead: [DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip](https://github.com/terrymacdonald/DisplayMagician/files/14288512/DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip)

**Closed** 2024-02-23 04:37 UTC
Labels: bug

**Comment by throbbie** [comment] 2024-02-23 04:39
That worked thankyou. Is there any scope in the future to allow this program to run and set a display profile from startup? It's not a big issue but would add quality of life to some users.

Once again, thank you for your work and attention on this post.

**Comment by terrymacdonald** [comment] 2024-02-23 05:04
Hi

Windows automatically applies the same display layout on start up that it
had when it was shutdown. DisplayMagician doesn't need to have that feature
as it is already built into Windows.

DisplayMagician is designed to be used via Game Shortcuts to change the
display layout the the one needed for a particular game, then run the game,
and then change everything back to the way it was before the game was
started. In this way the end result should always be that the display
layout will always end up in the display layout you want to use most of the
time.

If you haven't used game shortcuts in DisplayMagician yet then I would
strongly recommend you try that. It makes it a single click to run the
game, and DisplayMagician takes care of everything else.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2024-10-03 09:46
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry
