### ISSUE TITLE
Game Launcher no longer works with AMD GPU

### ISSUE THREAD

**Issue by Outerspacejunky16** [terrymacdonald/DisplayMagician#64] opened 2021-12-11 23:03 UTC
**Describe the bug**
Game Shortcuts no longer work after the most recent update. They were previously working before the update.

More detail:
Display Profiles functionality seems to work perfectly. I created 3 new display profiles:
Triple display without using AMD Eyefinity (3 monitors at 2560x1440)
Triple display using AMD Eyefinity (1 monitor at 7680x1440)
Single display using my single monitor
All of these were created after the DisplayMagician update. I then attempted to create a Game Shortcut using the standard procedure (see “To Reproduce section). When I complete the process and hit “Run”, my screen flashes, as if it is changing Display Profiles. But then the game does not start.

**To Reproduce**
Steps I used to create Game Shortcut
Open Display Manager
Click Game Shortcuts
Click New
Select one of my newly-made Display Profiles (let’s say Triple without Eyefinity)
Click tab 4 “Choose Game to start”
Ensure “Launch a Game executable” is selected
Choose the executable (e.g. C\Program Files (x86)\iRacing\iRacingSim64DX11.exe
Enter a Profile Name
Save Profile
Select Profile at Game Shortcut Library
Click “Run”

**Expected behaviour**
I expect the Display Profile to change to the one associated with the Game Shortcut, then for the game to launch. 

**Screenshots**
None included, please let me know if you’d like me to screenshot anything

**Reporting Logs**
See attached
[DisplayMagician-Support-20211207-2041.zip](https://github.com/terrymacdonald/DisplayMagician/files/7697864/DisplayMagician-Support-20211207-2041.zip)

**Environment (please complete the following information):**
 - Windows Version: Windows 10 Home
 - DisplayMagician Version 
 - Video Card: XFX AMD Radeon RX 6900 XT
 - Number and make/model of monitors: 3x LG 32GP83B-B.AUS. I also have 1x Dell P3421W. I had the issue even when I disconnected this monitor. 
 - Date of last video driver update: 2021-12-01 Radeon 21.12.1 (also had this issue with most previous version, 21.10.2 released on 2021-10-25)
 - Date of last windows update: 2021-11-11. No mandatory and no optional updates available (other than upgrade to Windows 11)

**Additional context**

**Comment by terrymacdonald** [comment] 2021-12-12 02:29
Hi @Outerspacejunky16  Thanks for logging the issue. I unfortunately don't have an AMD video card that will work with the latest AMD Radeon driver, so I can't do any testing for this issue. That means I'll need to rely on you to perform all the testing for me. Are you fine to do that?

But first - I have to ask - what version of DisplayMagician were you running just before 2.1.1? Just so I know what may have changed.

STEP 1:
Please download a new test version of DisplayMagician that I recently built. I've been troubleshooting another issue with an NVIDIA user that may also impact your situation and recently fixed it. So can you please try and download and install this test version and then see if you problem goes away? 
[DisplayMagicianSetup-v2.1.1.40.zip](https://github.com/terrymacdonald/DisplayMagician/files/7697735/DisplayMagicianSetup-v2.1.1.40.zip)

STEP 2:
OK, If that new test version of DisplayMagician didn't work, then we'll need to do some more in-depth testing. I'll be getting you to test the AMDLibrary functionality first up, and that library requires using Powershell to run some command line commands. Have you done that before? And if not, are you willing to give it a go?

I'll assume so, and give you some instructions below to perform up front to get things going.

In order to make sure that the custom AMDLibrary that I wrote is working ok, I have to get you to run a different test program that I wrote for it called AMDInfo. AMDInfo is designed to test only the AMDLibrary and the WinLibrary parts of DisplayMagician without any of the other bits. It allows us to confirm if the problem is in either of those two libraries, or if it is in DisplayMagician itself.

So can you please perform the following instructions EXACTLY as I've written them, and exactly in the same order as shown below. Both are critical to us finding and fixing the bug.

- Download the latest AMDInfo ZIP file from https://github.com/terrymacdonald/AMDInfo/releases, and save it to a folder on your PC
- Extract the AMDInfo ZIP file you just downloaded into a subfolder
- Within Windows File Explorer, right-click on the subfolder name while holding down the SHIFT key on the keyboard.
- That should give you an option to 'Open PowerShell window here'. Select that item.
- You should now have a Powershell window open and it should show the name of the subfolder.
- Type `AMDInfo.exe` and press enter. You should see something like this along with some other text:
![image](https://user-images.githubusercontent.com/5721772/145697876-afe6aaec-2f39-408c-8914-544f162cca78.png)

If you are seeing the text above then you're ready to carry on with the actual tests I need you to perform, So please do these in the exact order as below:

- Create a non-eyfinity display layout with some of your screens
- Save the first windows display as `AMDInfo save first.cfg`
- Rename the AMDInfo.log file to `Rename-Item -Path "AMDInfo.log" -NewName "AMDInfo-first-save.log"`
- Check if the first windows display config is equal with `AMDInfo equal first.cfg` (we want it to be equal)

Next create a second non-Eyefinity display layout:
- Create a windows display layout with different screens (turn some of the original screens off, and move other ones around, and change the primary monitor)
- Save the second windows display as `AMDInfo save second.cfg`
- Rename the AMDInfo.log file to `Rename-Item -Path "AMDInfo.log" -NewName "AMDInfo-second-save.log"`
- Check if the second windows display config is equal with `AMDInfo equal second.cfg` (we want it to be equal)

Next swap back to the first display layout:
- Load the first windows display as `AMDInfo load first.cfg`
- Rename the AMDInfo .log file to `Rename-Item -Path "AMDInfo.log" -NewName "AMDInfo-first-reload.log"`
- Check if the first windows display config is equal with `AMDInfoequal first.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `AMDInfo save first-reload.cfg`
- Make sure the second windows display config is NOT equal with `AMDInfo equal second.cfg` (we DO NOT want it to be equal)

Next swap back to the second display layout:
- Load the second windows display as `AMDInfo load second.cfg`
- Rename the AMDInfo.log file to `Rename-Item -Path "AMDInfo.log" -NewName "AMDInfo-second-reload.log"`
- Check if the second windows display config is equal with `AMDInfo equal second.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `AMDInfo save second-reload.cfg`
- Make sure the first windows display config is NOT equal with `AMDInfo equal first.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please upload the following files to this github issue by visiting here again in your web browser, and then click and drag the files over the issue. You may need to ZIP the file up before uploading them.
- first.cfg
- first-reload.cfg
- AMDInfo-first-save.log
- AMDInfo-first-reload.log
- second.cfg
- second-reload.cfg
- AMDInfo-second-save.log
- AMDInfo-second-reload.log

This test is specifically checking to make sure that the basic non-eyefinity changes will work on an AMD card. Once we have confirmed the non-eyefinity to non-eyefinity changes work, then we'll do the new round of tests.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-12-15 23:58
@Outerspacejunky16 Just in case you didn't get the edited version of the information above, please try and use this new test version of DisplayMagician. It includes the improvements we've made over the last few weeks.

[DisplayMagicianSetup-v2.1.1.41.zip](https://github.com/terrymacdonald/DisplayMagician/files/7723505/DisplayMagicianSetup-v2.1.1.41.zip)
 
**If you get any strange behaviour with a DisplayMagician display profile, please delete the Display Profile and create it again. Then update the Game Shortcuts using that Display Profile so that the use the replacement Display Profile** 

Please test the following things:
- Test that you can swap between different Display Profiles (if you have problems please delete the profile and create a new replacement)
- Test that you can create a cloned display profile
- Test that you can create a Eyefinity display profile
- Test that you can swap between all the profiles
- Test that you can use those profiles in some Game Shortcuts, and that the Game Shortcuts work properly.

If you can reply back in this issue with information about if it worked or not that would be great!

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-12-16 23:30
@Outerspacejunky16 I've just fixed the GUI display for multiple adapters in DisplayMagician v2.1.1.49 test version. I tested it on another computer with multiple adapters and it worked! So please install this new version and test this to make sure that it shows all your displays correctly: 
[DisplayMagicianSetup-v2.1.1.49.zip](https://github.com/terrymacdonald/DisplayMagician/files/7731026/DisplayMagicianSetup-v2.1.1.49.zip)

Thanks
Terry

**Comment by Outerspacejunky16** [comment] 2021-12-18 00:39
Terry,

I had planned to work through your troubleshooting request this weekend, but apparently my busy schedule paid dividends!  :)

As you might have guessed, v2.1.1.49 fixed any issues I previously had. Nice work! I'm sorry I couldn't be part of the solution.

**Comment by terrymacdonald** [comment] 2021-12-18 03:19
@Outerspacejunky16 Cool! So does that mean I'm able to close your issue now? Any other problems you've found?

Oh - and can you please test out this new version for me? I've made the windows all resizable. It's a little thing that's been nagging me for a while, so I wanted to get it fixed. Can you please test that the shortcut editing window works, and that the Display Profile window works? There is a possibility that a button or checkbox doesn't work now due to the changes I had to make. Would be great if you could test it for me so I'm sure everything works before the next release.

[DisplayMagicianSetup-v2.1.1.64.zip](https://github.com/terrymacdonald/DisplayMagician/files/7738642/DisplayMagicianSetup-v2.1.1.64.zip)

If everything is fixed, then I'll close this issue, and prepare for a new version of DisplayMagician!

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-12-19 08:36
Tested as working. Have now released the next release of DisplayMagician that fixes this issue. Closing issue.

Feel free to reopen if you'd like.

Thanks
Terry

**Closed by terrymacdonald** 2021-12-19 08:36 UTC
Labels: bug

**Comment by Outerspacejunky16** [comment] 2021-12-20 03:01
Hi Terry,

In the newest version, 2.1.2, in "Game Profiles", the "3. Choose what
happens before" option no longer works.The programs I've already saved in
their function as they should, but I can't add any new programs. When I
click "Add Start Program" nothing happens. It also does a weird thing with
the scrolling where I can't see the top program in the list.

I tried making a new game profile, same result.

Are you sick of me yet? :)

**Comment by terrymacdonald** [comment] 2021-12-20 05:02
Yeah, I accidentally introduced a bug there with the resizing work. Fix
will be released shortly.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-09 22:18
Hi @Outerspacejunky16 ,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, but it also has a few improvements to the AMDLibrary too. I don't have a supported AMD video card to test with unfortunately, so I was hoping you would be able to do some testing for me.

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles
- Test out Eyefinity, cloned displays, and see if anything breaks

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry
