### ISSUE TITLE
Unknown magic header: 123094056

### ISSUE THREAD

**Issue by kouettte** [terrymacdonald/DisplayMagician#179] opened 2022-12-21 19:25 UTC
**Describe the bug**
Display Magician crashes immediately on open.

**To Reproduce**
Steps to reproduce the behaviour:
I can reproduce 100% of the time, but since I don't know where the error comes from, I don't have a reproducer.

**Expected behaviour**
I would expect it to stay up, like it did for months.
I searched the registry for 123094056, but could not find anything.

**Screenshots**
N/A

Log:
...
2022-12-21 19:23:28.8187|TRACE|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: SteamGameKeyName is an int, so trying to see if it is an installed app|
2022-12-21 19:23:28.8187|TRACE|DisplayMagician.GameLibraries.SteamLibrary|SteamLibrary/LoadInstalledGames: SOFTWARE\Valve\Steam\Apps\805550 contains an 'Installed' value so is an installed Steam App.|
2022-12-21 19:23:28.8187|ERROR|DisplayMagician.Program|Program/Main general exception during app.Execute(args): |EXCEPTION OCCURRED :System.IO.InvalidDataException: Unknown magic header: 123094056
   at DisplayMagician.GameLibraries.SteamAppInfoParser.AppInfo.Read(Stream input)
   at DisplayMagician.GameLibraries.SteamAppInfoParser.AppInfo.Read(String filename)
   at DisplayMagician.GameLibraries.SteamLibrary.LoadInstalledGames()
   at DisplayMagician.GameLibraries.SteamLibrary.get_AllInstalledGames()
   at DisplayMagician.GameLibraries.GameLibrary.LoadGamesInBackground()
   at DisplayMagician.Program.<>c__DisplayClass32_0.<Main>b__5()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DisplayMagician.Program.Main(String[] args)
2022-12-21 19:23:28.8187|DEBUG|DisplayMagician.Program|Beginning to shutdown as the app command has finished executing.|
2022-12-21 19:23:28.8187|TRACE|DisplayMagician.Program|Closing the SplashScreen as it may still be open|
2022-12-21 19:23:28.8322|TRACE|DisplayMagician.Program|Program/Main: Clearing all previous windows toast notifications as they aren't needed any longer|
2022-12-21 19:23:28.8322|TRACE|DisplayMagician.Program|Program/Main: Stopping logging processes|

**Enviroment (please complete the following information):**
 - Windows Version: Win11
 - DisplayMagician Version v2.4.1.14
 - Video Card: Asus NVIDIA RTX4090
 - Number and make/model of monitors: 3xIiyama 43"
 - Date of last video driver update: Last week
 - Date of last windows update: today

**Comment by terrymacdonald** [comment] 2022-12-22 00:32
Hi @kouettte ,

Thanks for logging this issue. This is a duplicate of #173 .

You must have recently upgraded your Steam client to use the new steam beta. Steam have changed their file format, and DisplayMagician needs to be updated. I have already fixed in the codebase and have released a test version of DisplayMagician that I link to in issue #173. Feel free to check out that issue and install the new year version of DisplayMagician.

I'm hoping that I'll be able to release a new DisplayMagician update within the next week or two that permanently fixes this problem. I'm spending time with my family this week so that takes precedence 🙂.

Thanks
Terry

**Comment by kouettte** [comment] 2022-12-22 08:24
Thanks Terry,

 

I’ve installed the version from issue #173 <https://github.com/terrymacdonald/DisplayMagician/issues/173> , and it is now starting up correctly.

Thanks for the help, and enjoy the time with your family!

 

Regards,

 

                Yohan

**Closed** 2023-01-04 08:59 UTC
Labels: bug, duplicate, workaround
