### ISSUE TITLE
Profile does not apply correct color depth when using surround

### ISSUE THREAD

**Issue by ChrisWhatever1980** [terrymacdonald/DisplayMagician#84] opened 2022-01-25 15:36 UTC
**Describe the bug**
When applying a profile containing an Nvidia surround setup and 10bpc color depth, the color depth is set to 8bpc.

**To Reproduce**
In Nvidia settings:
1. Set the color depth to 10bpc
2. Activate surround.
3. The color depth is 8bpc.
4. Set the color depth to 10bpc again.

In DisplayMagician:
1. Create new profile.
2. Apply the profile.
3. The color depth is 8bpc.

**Expected behaviour**
Expected the color depth to stay at 10bpc. I realize this might be an issue of the nvidia graphics card driver itself. When activating surround manually from the nvidia settings, the color depth resets to 8bpc. I had hoped the profile would catch it and set it to 10bpc as I saved it.

**Enviroment (please complete the following information):**
 - Windows Version: Win10 Pro
 - DisplayMagician Version 2.1.5.5
 - Video Card: NVIDIA GTX 1080
 - Number and make/model of monitors: 2 custom projectors Zeiss Velvet SIM LED VISIR
 - Date of last video driver update: 25/01/22 (511.23)
 - Date of last windows update: System is not online, it has been a while.
[DisplayMagician-Support-20220125-1638.zip](https://github.com/terrymacdonald/DisplayMagician/files/7934896/DisplayMagician-Support-20220125-1638.zip)

**Comment by terrymacdonald** [comment] 2022-01-25 19:13
Hi Chris

Was this working fine before you upgraded your NVIDIA driver? If you've
only recently started using DisplayMagician, stop you're intake of it was
working in the past, then one thing to try is too uninstall the latest
511.23 nvidia drivers, and try something a bit older like the 472.12
drivers.

https://www.nvidia.com/Download/Find.aspx?lang=en-us

If you can try the older driver, a and the older driver works, then we'll
know for sure where the issue is.

My gut feel is that is the driver. I unfortunately only have one HDR screen
in my triples, so I can't test HDR in surround mode here. I'll have to rely
on what you can find.

Thanks
Terry

**Comment by ChrisWhatever1980** [comment] 2022-01-25 22:54
Hi Terry, thanks for answering so quickly.
I updated to 511.23, because it wasn't working with the previous version, ..417.something
I think you are right, the bug is in the driver.

Btw, the bpc are set correctly when applying a profile containing mosaic mode on quadro cards.

I might have to make a batch file that switches to the profile, sleeps x seconds, then resets the bpc with another tool such as http://tools.taubenkorb.at/change-screen-resolution

Thanks for your feedback!

**Comment by terrymacdonald** [comment] 2022-01-25 23:17
Also, I remember there have been some HDR improvements over the last few Windows 10 updates. There were some issues between Win HDR and the NVIDIA custom HDR, and IIRC from some forum posts some of them were resolved with improvements to Win HDR. This could be applicable in your particular situation.

I would always recommend updating Windows to the latest patches, from a security point of view, as well as the fact that I do all my testing on either a fully patched Windows 10 machine or a fully patched Win 11 machine.

Another important point to make is that DisplayMagician doesn't ever create a display configuration itself - it ONLY reads what the NVIDIA driver gives it and stores it for later, and then tries to set that config up again using the NVIDIA driver when you tell DisplayMagician to do so. 

When looking at your config files, it looks like your 'SingleMode120' display profile has 10 bit pixel count set ok, but the NVIDIA HDR mode is set to off. This means that HDR settings won't be set, and therefore the 10-bit BPC won't be set. You can see that with the HdrMode = 0 (off) and the HdrBpc = 3 (10-bit) in the structure below:

```
"HdrColorData": {
          "2147881095": {
            "Version": 131124,
            "Cmd": 0,
            "HdrMode": 0,
            "StaticMetadataDescriptorId": 0,
            "MasteringDisplayData": {
              "DisplayPrimaryX0": 0,
              "DisplayPrimaryY0": 0,
              "DisplayPrimaryX1": 0,
              "DisplayPrimaryY1": 0,
              "DisplayPrimaryX2": 0,
              "DisplayPrimaryY2": 0,
              "DisplayWhitePointX": 0,
              "DisplayWhitePointY": 0,
              "MaxDisplayMasteringLuminance": 0,
              "MinDisplayMasteringLuminance": 0,
              "MaxContentLightLevel": 0,
              "MaxFrameAverageLightLevel": 0
            },
            "HdrColorFormat": 0,
            "HdrDynamicRange": 0,
            "HdrBpc": 3
          }
        },
```

This means that when DisplayMagician grabbed the config from the NVIDIA driver, the NVIDIA driver had turned off HDR itself before the config got to DisplayMagician.  This lines up with what I found when testing this functionality - I discovered that NVIDIA HDR and Win HDR work in tandem together to change each others HDR settings. If there is an HDR mode set that Windows doesn't like then NVIDIA seems to disable it's own HDR settings. Sometimes it happens in the other direction too. This might be happening in your case?

Personally, my next step if I were you would be to patch Windows 10 to the latest versions, and then try again. Also, I would then recreate all my display profiles once that was done, as they all see to have the NVIDIA HDR turned off when DisplayMagician read the configuration.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-01-25 23:21
You could always try setting the BPC through Windows itself rather than through the NVIDIA HDR settings? That might work better.

**Comment by ChrisWhatever1980** [comment] 2022-01-26 13:45
Hey Terry, I'll try setting the HDR via Windows and Nvidia and see what happens. If that doesn't work I'll go about updating Windows, which might keep me busy until next week. Thanks so much for taking the time to look into my problem. I appreciate it. I'll get back to you when I have news. Cheers!

**Comment by terrymacdonald** [comment] 2022-02-04 18:07
Hi @ChrisWhatever1980 ,

Any updates? We're getting closer to a V2.2.0 release, and if like to figure out a fix for your problem and roll it into the next release of I can.

Thanks
Terry

**Comment by ChrisWhatever1980** [comment] 2022-02-04 20:03
HI Terry,

I can't tell windows itself to use HDR, the option is greyed out. I tried to set the 10bpc in various ways/orders, but I couldn't get it to save it either.

I downloaded the nvapi and found the sample DisplayColorControl which does the very thing. 
So I call DisplayMagician with the profile parameter from a batch file, sleep for 5 seconds and then call the DisplayColorControl executable to reset to 10bpc.
That works for the moment.

I noticed that the Nvidia control has some trouble with the mosaic mode anyway. Each time I activate it I have to reconfigure it. It does not save a mosaic configuration even though parts of the ui (you can give the config a name) and parts of the nvapi (functions that enable current topology) suggest so. I noticed your post in the nvidia forums asking about the same thing: https://forums.developer.nvidia.com/t/the-best-way-to-programmatically-store-and-reload-a-nvidia-mosaic-topology/200648
Did they ever get back to you?

Unfortunately, other tasks demand my attention so I can't pursuit it further. Especially, since we have a solution we can live with. I will eventually post an update when I get around to updating the computers.
Thanks for helping so much, warms my heart to see you put so much energy and dedication into your project. DIsplayMagician truly helps me a lot :)
 
Best Regards, 
Chris

**Comment by terrymacdonald** [comment] 2022-02-05 03:11
Hi Chris,

Ok. I'll close this issue for now then so that I know I no longer need to
work on it. Feel free to reopen of you need to when you get some time free.

Thanks
Terry

**Closed** 2022-02-05 08:31 UTC
Labels: bug
