### ISSUE TITLE
No titles are launching

### ISSUE THREAD

**Issue by jbretthorton** [terrymacdonald/DisplayMagician#88] opened 2022-02-12 15:07 UTC
**Describe the bug**
After no perceived updates, no titles (Sims) launch after previously working correctly. I have uninstalled - reinstalled, completely deleted all profiles and started over. The program seems to be working perfectly fine until I click on a link (or right click and select run) nothing happens. I have tried all my sims in new links as well.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json` 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

**Enviroment (please complete the following information):**
 - Windows Version: Windows 10
 - DisplayMagician Version 2.1.5
 - Video Card: NVIDIA RTX 3080
 - Number and make/model of monitors: 3 MSI Optix MAG321CQR
 - Date of last video driver update: Jan someting, but up tp date as of 3 or 4 days ago
 - Date of last windows update: no idea, but up to date

**Additional context**
[DisplayMagician-Support-20220212-1003.zip](https://github.com/terrymacdonald/DisplayMagician/files/8053776/DisplayMagician-Support-20220212-1003.zip)

**Comment by terrymacdonald** [comment] 2022-02-17 18:29
Hi @jbretthorton,

Are you saying that no games at all run? Or just no Sims titles run? Which game launcher are you using to launch the Sims games? 

Thanks
Terry

**Comment by jbretthorton** [comment] 2022-02-17 18:46
No Sims launch from your launcher.Running simhub, simtools, crew chief on the side. AC, ACC, AMS2, RRE, etc, none launch from your launcher. They all did previously just fineThanks,Brett Horton
-------- Original message --------From: terrymacdonald ***@***.***> Date: 2/17/22  1:29 PM  (GMT-05:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: jbretthorton ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] No titles are launching (Issue #88) 
Hi @jbretthorton,
Are you saying that no games at all run? Or just no Sims titles run? Which game launcher are you using to launch the Sims games?
Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-02-17 19:15
Hi,

Sorry, I was meaning which game launcher Sims was installed in... Steam,
Uplay, GOG, Epic, etc. In other words did you choose some from a list of
your games in DisplayMagician, or did you select the exe file in the
application section?

That is weird about all the games not working. I'll have a look through
your logs this weekend.

Thanks
Terry

**Comment by jbretthorton** [comment] 2022-02-17 19:39
Rgr, sorryAll through steamThanks,Brett Horton
-------- Original message --------From: terrymacdonald ***@***.***> Date: 2/17/22  2:15 PM  (GMT-05:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: jbretthorton ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] No titles are launching (Issue #88) 

Hi,



Sorry, I was meaning which game launcher Sims was installed in... Steam,

Uplay, GOG, Epic, etc. In other words did you choose some from a list of

your games in DisplayMagician, or did you select the exe file in the

application section?



That is weird about all the games not working. I'll have a look through

your logs this weekend.



Thanks

Terry

**Comment by terrymacdonald** [comment] 2022-03-06 10:15
Sorry Brett, I've been deep in the internals of Windows trying to set windows taskbar locations using windows internal messages for the last 4 weeks. It's not worked as I want to, so I'm coming back to going through the existing bugs I have in order to add them to the next version of DisplayMagician. I should be able to review your logs properly in the next two weeks or so. 

Just wanted to keep you updated.

Thanks
Terry

**Comment by jbretthorton** [comment] 2022-03-06 15:09
All good man, keep up the good work
    On Sunday, March 6, 2022, 05:15:16 AM EST, terrymacdonald ***@***.***> wrote:  
 
 


Sorry Brett, I've been deep in the internals of Windows trying to set windows taskbar locations using windows internal messages for the last 4 weeks. It's not worked as I want to, so I'm coming back to going through the existing bugs I have in order to add them to the next version of DisplayMagician. I should be able to review your logs properly in the next two weeks or so.

Just wanted to keep you updated.

Thanks
Terry

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by terrymacdonald** [comment] 2022-04-09 22:00
Hi @sven25,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-11 20:18
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-14 09:32
@jbretthorton New build time! I *think* I've fixed the issues you've experienced. 

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts. 

[DisplayMagicianSetup-v2.3.0.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8488041/DisplayMagicianSetup-v2.3.0.50.zip)

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a  Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by jbretthorton** [comment] 2022-04-14 10:45
Thanks for the update sir! your work is appreciated 

    On Thursday, April 14, 2022, 05:32:45 AM EDT, terrymacdonald ***@***.***> wrote:  
 
 


@jbretthorton New build time! I think I've fixed the issues you've experienced.

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts.

DisplayMagicianSetup-v2.3.0.50.zip

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by terrymacdonald** [comment] 2022-04-15 07:01
@jbretthorton I think this version will work for you. Can you please install this version instead of the one I suggested in previous comments and test that the problem is fixed, and then report back here.
[DisplayMagicianSetup-v2.3.1.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/8494408/DisplayMagicianSetup-v2.3.1.7.zip)

If the issue is fixed then please also close this issue so I can keep track of when I can release this new version to the general population.

Thanks
Terry

**Comment by jbretthorton** [comment] 2022-04-15 10:38
Wilco
    On Friday, April 15, 2022, 03:02:07 AM EDT, terrymacdonald ***@***.***> wrote:  
 
 


@jbretthorton I think this version will work for you. Can you please install this version instead of the one I suggested in previous comments and test that the problem is fixed, and then report back here.
DisplayMagicianSetup-v2.3.1.7.zip

If the issue is fixed then please also close this issue so I can keep track of when I can release this new version to the general population.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-16 06:03
@jbretthorton Another build with a couple of additional fixes that other users have reported.

The exception error when showing/saving a new profile should be fixed now. As should the detecting of the main game shutting down. You can test the new version works by downloading DisplayMagician v2.1.3.12 from here:
[DisplayMagicianSetup-v2.3.1.12.zip](https://github.com/terrymacdonald/DisplayMagician/files/8499351/DisplayMagicianSetup-v2.3.1.12.zip)

There is only one more small bug that I'm aware of that I'm trying to fix but it only seems to happen with some specific start programs and only when run from a desktop shortcut. Hoping to fix that within the next few days.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-19 10:27
@jbretthorton  I have worked through many issues over the last week, so I recommend that you do some testing with this version:
[DisplayMagicianSetup-v2.3.1.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8512144/DisplayMagicianSetup-v2.3.1.50.zip)

I **strongly** recommend that  you delete your old display profiles and recreate them again just to be 100% sure you're running the latest versions of the file, and then updated your game shortcuts to use those new profiles.

This version fixes all the bugs that I know about, and based on my testing is just about ready to release to the general public. I'd really appreciate it if you could do some testing (but only if you have some spare time) so that I will know if it really does fix all the issues.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-20 20:40
@jbretthorton I've just released a new version of DisplayMagician that should fix the issue you're experiencing. Please download DisplayMagician v2.3.1.60 from [https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.3.1](https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.3.1) and see how things go.

I will close this issue for now, but if you have exactly the same issue then please reopen this case. If you have a brand new issue that is different, then please log a [new issue](https://github.com/terrymacdonald/DisplayMagician/issues/new/choose).

Thanks
Terry

**Closed by terrymacdonald** 2022-04-20 20:40 UTC
Labels: bug
