### ISSUE TITLE
Desktop context menu shortcuts no longer work.

### ISSUE THREAD

**Issue by c1em3ntchua** [terrymacdonald/DisplayMagician#180] opened 2022-12-27 00:41 UTC
**Describe the bug**
As above. It worked again when I reverted back to v2.3.1. Taskbar shortcut (bottom right corner) -> 'Change Display Profiles' work as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Right-click on Desktop -> 'DisplayMagician Profiles' -> Select shortcut

**Expected behaviour**
The selected profile does not activate.

**Screenshots**
N/A

**Reporting Logs**
[DisplayMagician-Support-20221227-0838.zip](https://github.com/terrymacdonald/DisplayMagician/files/10305117/DisplayMagician-Support-20221227-0838.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Windows 11 Pro 21H2 Build 22000.1335
 - DisplayMagician Version: 2.4.1.14
 - Video Card: EVGA RTX 3080 FTW3 Ultra
 - Number and make/model of monitors: 3xAcer XB271HU, 1x Denon AVR
 - Date of last video driver update: 2021-10-27 (Geforce Game Ready Driver 527.56)
 - Date of last windows update: 2022-12-15

**Comment by terrymacdonald** [comment] 2022-12-27 07:30
Hi @c1em3ntchua,

This bug has already been fixed in the codebase in this commit: https://github.com/terrymacdonald/DisplayMagician/commit/7513196fe148f89a12a2959613a9f4d1515c7d4d

I noticed this issue when doing some prior testing in November so fixed it then. I'm currently nearing a new release, but have been fixing some of the new functionality that I've been working and I need to ensure that is all working before I roll out the new version to all users.

If you'd like to test a version that fixes the issue you are experiencing, then feel free to download the current latest test version of DisplayMagician from here: [DisplayMagicianSetup-v2.5.0.331.zip](https://github.com/terrymacdonald/DisplayMagician/files/10235613/DisplayMagicianSetup-v2.5.0.331.zip)

You can download and unzip the file, and then run the setup msi file to install an updated version of DisplayMagician.

Please log any new issues you find under a different issue, so that I can track and fix them separately.

I'm going to close this issue now, as the issue is fixed in the codebase. Closing this issue will let me concentrate on the issues I still have to fix.

Thanks
Terry

**Closed by terrymacdonald** 2022-12-27 07:30 UTC
Labels: bug

**Comment by c1em3ntchua** [comment] 2022-12-27 10:14
Hi @terrymacdonald,

Thanks for the quick response. The test version works well.

**Comment by terrymacdonald** [comment] 2022-12-28 05:33
Excellent! Great to hear it works.

Thanks
Terry
