### ISSUE TITLE
switch from 2 monitor to 3 doesn't work

### ISSUE THREAD

**Issue by ganzoni** [terrymacdonald/DisplayMagician#284] opened 2024-01-25 08:29 UTC
When i switch from 2 monitors to 3, the monitor boot up, but goes back to sleeping mode.

It's as if he can't activate the screen in the video settings.

My version is 2.5.0.352

[DisplayMagician-Support-20240125-0921.zip](https://github.com/terrymacdonald/DisplayMagician/files/14048923/DisplayMagician-Support-20240125-0921.zip)

**Comment by terrymacdonald** [comment] 2024-01-28 08:48
@ganzoni  I did find some issues with the earlier v2.5 version. I've made a lot of revisions to how DisplayMagician works in a test version v2.6.0.485 (attached) that should make it way more reliable. But it is highly likely you will need to 'update' your Display Profiles to make them work properly.

I'd recommend first of all applying a Display Profile, and then press the 'update' button (new for v2.6). That will recreate the config for the Display Profile and should make it work properly. You'll need to do that to each of your saved Display Profiles. Then please test out changing between your Display Profiles to see if everything works as expected.

Here is the latest test version of DisplayMagician: 
[DisplayMagicianSetup-v2.6.0.485.zip](https://github.com/terrymacdonald/DisplayMagician/files/14075432/DisplayMagicianSetup-v2.6.0.485.zip)

Thanks for all your help testing.

Terry

**Comment by ganzoni** [comment] 2024-01-28 09:01
Hi, I installed the V. 2.6.0.485 but it doesn't boot up, i can't start it!

Sorry for my bad english, i'm french ;-)

**Comment by ganzoni** [comment] 2024-01-28 09:09
When i start the V. 2.6.0.485 it boot up and crashed direct.

**Comment by terrymacdonald** [comment] 2024-01-28 09:21
Darn it. Can you please zip up your DisplayMagician folder and attach it to
this issue? I will be able to see what the error is and fix it.

The DisplayMagician folder is in
C:\Users\<user>\AppData\Local\DisplayMagician\

To get you going again while I troubleshoot, you have two options:

1. Uninstall DisplayMagician v2.6 and install v2.5 again. That should work.
Or...

2. Rename the DisplayMagician folder to something like DisplayMagicianOld,
and then restart DisplayMagician. It should start up, but you will need to
recreate your display profiles and your game shortcuts.

I'll try having a look tomorrow morning to see if I can fix your errors, if
you can upload your zipped up DisplayMagician folder for me to review.

Also, your English is great! No need to apologise. It's way better than my
French.

Thanks
Terry

**Comment by ganzoni** [comment] 2024-01-28 09:34
here the folder 
[DisplayFusion.zip](https://github.com/terrymacdonald/DisplayMagician/files/14075507/DisplayFusion.zip)

**Comment by ganzoni** [comment] 2024-01-28 09:39
I removed the V. 2.6.0.485 and installed the older version, the v. 2.5.0.352 launched well.

**Comment by terrymacdonald** [comment] 2024-01-28 19:43
@ganzoni You sent me a DisplayFusion ZIP File.... they're my 'competitor' :D. Can you please upload your DisplayMagician folder instead? The DisplayMagician folder is in C:\Users\<user>\AppData\Local\DisplayMagician\

I can't use DisplayFusion information unfortunately.

Thanks
Terry

**Comment by ganzoni** [comment] 2024-01-28 20:31
Oups sorry ;-)
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/14077625/DisplayMagician.zip)

**Comment by terrymacdonald** [comment] 2024-01-29 00:18
No problems. It did make me laugh out loud though :).

Thanks

*Terry*

**Comment by terrymacdonald** [comment] 2024-01-29 00:38
@ganzoni Hmmm everything looks perfectly fine in all your configs. And directory structures look good.

Do you know if you have installed the .Net Framework 4.8.1 runtime on your PC? Tis version of DisplayMagician uses .Net Framework 4.8.1, and I'm wondering if that's what's missing from your PC preventing DM to start?

We can fairly easily test this:

- Download and install .Net Framework 4.8.1 Runtime  from https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer
- Install this new latest version of DisplayMagician that I just compiled with some extra bugfixes I updated last night: [DisplayMagicianSetup-v2.6.0.492.zip](https://github.com/terrymacdonald/DisplayMagician/files/14078483/DisplayMagicianSetup-v2.6.0.492.zip)
- Restart your PC
- Test to see if it will run 🤞 


I really hope this is the fix, as then I know what needs fixing!

Thanks
Terry

**Comment by ganzoni** [comment] 2024-01-29 05:47
The .Net Framework was allready installed!

I installed your new version, it bootet up 1 time, when i clic on anything i get an error and it crashed, look the attached file, may be it can help you.

[error.txt](https://github.com/terrymacdonald/DisplayMagician/files/14080057/error.txt)

**Comment by ganzoni** [comment] 2024-01-29 05:57
And here the log file from DisplayMagician
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/14080128/DisplayMagician.log)

**Comment by terrymacdonald** [comment] 2024-01-29 07:08
This is perfect @ganzoni! You gave me exactly what I need I think!

The error is that the AMD library is complaining when there isn't the AMD driver installed. This is exactly what I need! Thank you so much.

Terry

**Comment by terrymacdonald** [comment] 2024-01-30 23:10
Thanks @ganzoni ,

I think I know what's happening thanks to your help, and I think I've developed a fix for the issue. I've attached a new test version of DisplayMagician to this, and hopefully it works ok for you.

[DisplayMagicianSetup-v2.6.0.505.zip](https://github.com/terrymacdonald/DisplayMagician/files/14105335/DisplayMagicianSetup-v2.6.0.505.zip)

The fix has the following checks in it: 

- It checks if the DLL for NVIDIA or AMD is present. If not it just returns a default empty config that that library.
- If the DLL is present it checks if there is a video card present for NVIDIA or AMD. If not it just returns a default empty config that that library.
- If the DLL is present it and there is a matching video card for that vendor, it checks if there are any connected displays through NVIDIA or AMD. If not it just returns a default empty config that that library.
- After those checks it then attempts to get the config.

Previously only the first check was being done, and that would cause issues in desktop PCs with only one vendors card, or in gaming laptops with both AMD and NVIDIA. I'm hoping this will now work.

Thanks
Terry

**Comment by ganzoni** [comment] 2024-01-31 06:20
It work good now, BUT ;-)

The first problem persits, when i want to switch from 1 screen to more (2 screens) the second screen boots up and goes down!

But when i press **several times** the hotkey for 2 screens during the booting phase it works!

May be can you give the hotkey signal to boot up the others screens for a longer time or repeat it for 3-5 seconds or someting like this?

[DisplayMagician-2024-01-31-0700.log](https://github.com/terrymacdonald/DisplayMagician/files/14107954/DisplayMagician-2024-01-31-0700.log)

**Comment by ganzoni** [comment] 2024-01-31 06:26
After some more tests (also with triple screen)

I need to press **2 times** the hotkey, and it works!

**Comment by terrymacdonald** [comment] 2024-01-31 07:38
This is great news! So the first issue seems to be fixed....

The original problem you had though still needs sorting out... ok - so can
you please create a new Support ZIP File and upload it to this issue? I now
record the logs for the last 5 starts so I should be able to see what has
happened when you have managed to get it working. THe logs should hopefully
provide me with a guide to where the problem could be.

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com

**Comment by ganzoni** [comment] 2024-01-31 16:41
Here the zip

[DisplayMagician-Support-20240131-1740.zip](https://github.com/terrymacdonald/DisplayMagician/files/14114576/DisplayMagician-Support-20240131-1740.zip)

**Comment by terrymacdonald** [comment] 2024-02-02 04:53
ok @ganzoni , I've added in more checks and logic to avoid crashes. Could you please try this version and see if the hotkey works the first time now? 
[DisplayMagicianSetup-v2.6.0.508.zip](https://github.com/terrymacdonald/DisplayMagician/files/14135107/DisplayMagicianSetup-v2.6.0.508.zip)

I'm hoping this will work, but at the very least it should allow DisplayMagician to boot up enough for you to create a Support ZIP File. Let's see whether I've fixed it 🤞.

**Comment by ganzoni** [comment] 2024-02-02 20:37
Hi,

No, it's the same, i need to use a second time the hotkey when the screens are booted up to making it work.
________________________________
De : terrymacdonald ***@***.***>
Envoyé : vendredi, 2 février 2024 05:53
À : terrymacdonald/DisplayMagician ***@***.***>
Cc : ganzoni ***@***.***>; Mention ***@***.***>
Objet : Re: [terrymacdonald/DisplayMagician] switch from 2 monitor to 3 doesn't work (Issue #284)


ok @ganzoni<https://github.com/ganzoni> , I've added in more checks and logic to avoid crashes. Could you please try this version and see if the hotkey works the first time now?
DisplayMagicianSetup-v2.6.0.508.zip<https://github.com/terrymacdonald/DisplayMagician/files/14135107/DisplayMagicianSetup-v2.6.0.508.zip>

I'm hoping this will work, but at the very least it should allow DisplayMagician to boot up enough for you to create a Support ZIP File. Let's see whether I've fixed it 🤞.

**Comment by terrymacdonald** [comment] 2024-02-03 07:55
Can you please try to change your profiles using Apply button in the
display profile window? I'd like to know if it acts the same way pursuing
the Apply button as it does with the hotkey. Do you need to press the Apply
button twice to get the taskbars in the same place?

Thanks
Terry

**Comment by terrymacdonald** [comment] 2024-02-03 10:21
Sorry - I was meaning trying the Apply button, then once it has applied,
try pressing the hotkey to see if that works. I'm trying to figure out a
pattern that could work to then figure out which part of the complicated
display change logic might be at fault.

Thanks
Terry

**Comment by thebaz** [comment] 2024-02-03 20:55
I silently tried (silently until now) every single 2.6.0.x releases... The app never launched... Had to uninstall and go back to 2.5.x every time
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/14154255/DisplayMagician.zip)

**Comment by terrymacdonald** [comment] 2024-02-04 02:00
@thebaz - The log files you sent seem to be related to an earlier version of DisplayMagician. The settings file shows that 2.5.0.352 was the last application that you ran, and the log file looks like it was the older version as well.

I'll need a bit more detail in order to help you out:

- Is your issue specifically related to switching from 2 monitors to 3 monitors? Or is it related to the application not starting?
- What was the last version of the v2.6.0 test version s did you try? The latest version at the moment is v2.6.0.509 (see below).
- What system are you running? What CPU do you have? 
- How many displays do you have? 
- What are the manufacturer and model of them?
- How is each display connected to your video card?
- Do you have more than one GPU in your PC?
- Do you have an integrated GPU (iGPU) as well as a discrete GPU (dGPU)?

In order for me to check what issue you have , please install the latest version of  DisplayMagician
[DisplayMagicianSetup-v2.6.0.509.zip](https://github.com/terrymacdonald/DisplayMagician/files/14152802/DisplayMagicianSetup-v2.6.0.509.zip)

Then next try to run DisplayMagician and see if that works. If it doesn't work please send me the DisplayMagician config folder again (with the new logs in it) and we'll try troubleshooting from there.

Thanks
Terry

**Comment by thebaz** [comment] 2024-02-04 10:32
Hello Terry.

I was finally able to have the application running; I did 1) uninstall the previous 2.5.0.352 version 2) remove the DisplayMagician folder from its location 3) install the 2.6.0.509 version 4) restart the PC

This way I was finally able to have DisplayMagician running (so as you can understand my issue was related to the application not running)

I rebuilt the Display Profiles and then copied the game shortcuts I had and updated accordingly to the display profiles

BTW, here are the details you asked for:
I am running Windows 11 23H2 22631.3085; the CPU is a "13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz"
I have 4 displays
3 of them are: Samsung Odissey G50A 32"; 1 is a Samsung S22F350
the 3  Samsung Odissey G50A are connected by DisplayPort; the 1 Samsung S22F350 is connected by HDMI
I just have 1 GPU card (NVIDIA GeFroce RTX 3090 with the latest released drivers)
I do not have an iGPU
I am attaching this latest config folder

Best,
Luca
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/14156364/DisplayMagician.zip)

**Comment by ganzoni** [comment] 2024-02-05 05:40
Hi Terry,

I tested the 509 version, it changed nothing. ;-)
Either the hotkey or apply buton.

**Comment by terrymacdonald** [comment] 2024-02-05 08:50
Hmmmm. This is useful information thanks. Helps me eliminate potential
places that be causing the bug.

 I'm trying to redevelop my code with the GDI settings to see if I can set
things in a different way. If I discover anything new I'll shoot you a new
test version to try.

Thanks
Terry

**Comment by ganzoni** [comment] 2024-02-05 18:22
I have a new issue, my sort cuts are "CTRL (left) + ALT (left) + 1 (for 1 screen, 2 for 2 screens and 3 for 3 screens)".

But now when i use "ALT GR (right) + 1 (2 or 3)" it change the settings????

**Comment by terrymacdonald** [comment] 2024-02-05 18:56
Hi @ganzoni,

Are you saying that you have 3 hotkeys set,  one for each display profile?
And that you use the left CTRL+ left ALT and a number to get to them? If
so, I understand that part correctly.

I'm a bit confused for the second part of your comment. Are you saying that
you suggested have all now moved to left CTRL + right ALT and a number ?

If I've understood that correctly, then it's nothing I've changed in the
code. I haven't touched that at all. If anything has happened then the
NHotkey library was possibly updated with a change in behaviour.

Can you please log a new issue so that I can work on that separately? I
need to keep different issues in different places so that I can keep track
of them before the next release.

I'll shortly send you a new test version of DisplayMagician that skips
using the GDI API just in case that one is causing the taskbar issue for
you.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2024-02-05 20:13
@ganzoni Here is a new test version of DisplayMagician. It only uses the CCD API to se t the windows positions. I want to see if that helps make setting the taskbar position more reliable or not. Please check it out and report your findings back.

[DisplayMagicianSetup-v2.6.0.511-no-gdi.zip](https://github.com/terrymacdonald/DisplayMagician/files/14171483/DisplayMagicianSetup-v2.6.0.511-no-gdi.zip)

Thanks
Terry

**Comment by ganzoni** [comment] 2024-02-06 09:24
Hi Terry,

I'm not sure what you want test?

It's the same than before.
[cid:48348510-f96d-4f39-9b2e-d133c4b0e385]
________________________________
De : terrymacdonald ***@***.***>
Envoyé : lundi 5 février 2024 21:14
À : terrymacdonald/DisplayMagician ***@***.***>
Cc : ganzoni ***@***.***>; Mention ***@***.***>
Objet : Re: [terrymacdonald/DisplayMagician] switch from 2 monitor to 3 doesn't work (Issue #284)


@ganzoni<https://github.com/ganzoni> Here is a new test version of DisplayMagician. It only uses the CCD API to se t the windows positions. I want to see if that helps make setting the taskbar position more reliable or not. Please check it out and report your findings back.

DisplayMagicianSetup-v2.6.0.511-no-gdi.zip<https://github.com/terrymacdonald/DisplayMagician/files/14171483/DisplayMagicianSetup-v2.6.0.511-no-gdi.zip>

Thanks
Terry

**Comment by ganzoni** [comment] 2024-02-07 05:36
Hi Terry.

EVERYTHING is working perfect with V512, well done!!!!

But i have still the issue https://github.com/terrymacdonald/DisplayMagician/issues/288

**Comment by terrymacdonald** [comment] 2024-02-07 09:18
This is great news!

I will have one more version to test. This last one is for completeness, so
I can confirm that the issue was indeed the NVIDIA NvAPI SetDisplayConfig
function. I will add the GDI calls back in to DM but will leave the
SetDisplayConfig disabled.

If you can test that again that will let us know if GDI is involved in any
way in this issue, and if it's not then we can add that back in.

One final test then we'll work on your hotkey thing.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2024-02-07 20:02
@ganzoni Here should be the last test version for this problem. As mentioned last time it will test that adding GDI back in still works. I'm not 100% that I will add it back in to the production release, but I still want to test so I know where the problem is.

[DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip](https://github.com/terrymacdonald/DisplayMagician/files/14200905/DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip)

After this test is complete I'll provide another version for you to use until the final release is ready.

Thanks for all your help so far!

Terry

**Comment by ganzoni** [comment] 2024-02-08 06:08
Everything works perfectly!!!!!

**Comment by terrymacdonald** [comment] 2024-02-08 06:51
Perfect! That's really great to know. And thank you so much for your
donation. I really do appreciate it when people decide to gift me a
donation. Thanks you, it means a lot.

Ok, I'll close this issue I think as we're done with it.

Thanks
Terry

**Closed** 2024-02-08 21:20 UTC
Labels: bug
