### ISSUE TITLE
Windows 11 and Taskbar

### ISSUE THREAD

**Issue by guennid** [terrymacdonald/DisplayMagician#52] opened 2021-11-05 10:12 UTC
I have a problem after updating to Windows 11.
If i switch back from Nvidia surround to normal mode with Triple Screens, sometimes the Taskbar is on top of the main screen. It doent happens every time.  But it is tricky, cause in Windows 11 you can choose the taskbar be on top or bottom. 

Günter

**Comment by terrymacdonald** [comment] 2021-11-05 22:57
@guennid What version of DisplayMagician are you currently using? v1.1.4 or v2.0.1?

I've been developing a new version of DisplayMagician v2.1.0 which hopefully fixes this issue for good. 

Can you please download and install this **test version** 2.1.0.160 over the top of your current install. Please note you will need to recreate your DisplayProfiles, as we use a brand new file format which has all the extra settings used to track those sorts of set up.

[DisplayMagicianSetup-v2.1.0.160.zip](https://github.com/terrymacdonald/DisplayMagician/files/7480411/DisplayMagicianSetup-v2.1.0.160.zip)

Please reply back here if the issue is fixed, as I need the results of your testing to know if DisplayMagician v2.1.0 is ready to release as the next official version.

Thanks
Terry

**Comment by guennid** [comment] 2021-11-06 08:19
@terrymacdonald I have installed your new version. Befor this i had 2.0.1.
So i tested the new software. But i have the same issue. After switching 2 or 3 times between surround and normal i came back to normal with the taskbar on top. 
Günter

**Comment by terrymacdonald** [comment] 2021-11-07 09:14
Hi Günter,

I need your DisplayMagician.log file, and your config files, to try and see where the issue may lie.

Can you please:

- Open DisplayMagician and change between you different display profiles until there is an error.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Came back here, and upload the Support Zip File through your web browser to this issue.

That should hopefully give me the information I need to do some troubleshooting.

Can you also please fill this list out of your current setup:
 - Windows Version: [e.g. Win10]
 - DisplayMagician Version [e.g. 1.1.0]
 - Video Card: [e.g. Asus NVIDIA GTX1070]
 - Number and make/model of monitors: [e.g. 2xDell UH2718H, 1x LG G27U17D]
 - Date of last video driver update: [e.g. 2021-02-15]
 - Date of last windows update: [e.g. 2021-02-15]

That will also give me some more information with which to troubleshoot.

If I can't find an error in here, then we'll need to test the NVIDIALibrary used within DisplayMagician. I have written some test software called NVIDIAInfo which contain the NVIDIALibrary I made to make video library changes on a NVIDIA graphics card. We may need to do some further testing with NVIDIAInfo if the Support Zip File and your description of your current setup don't provide enough infromation.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-11-13 20:35
Hi @guennid ,

We've recently found and fixed an error with the Windows Library and NVIDIA Library that I made. It would come up with an error when it was validating a config, and that would stop the windows portion of the display config being applied. This is highly likely what was causing your issue. This is now fixed.

Additionally, we had an issue with the NVIDIA Library not correctly applying colour information and failing if a screen with colour information was turned off in a profile. This too has been fixed.

And lastly, the doubled Steam information is fixed. I was accidentally adding the base steam library to the config twice, so all games in the base game library were being scanned twice (doh!). This has been fixed too.

Could you please update your DisplayMagician and test this version? [DisplayMagicianSetup-v2.1.0.215.zip](https://github.com/terrymacdonald/DisplayMagician/files/7531681/DisplayMagicianSetup-v2.1.0.215.zip). I think most of the bugs are now squashed, so I'm sending this copy to my faithful testers to doublecheck the reliability on their own computers.

IMPORTANT: I strongly recommend deleting all your existing Display Profiles and recreating them again. This will ensure that your Display Profiles have all the latest fixes applied to them. Once you recreate the Display Profiles you can then go through your shortcuts and update them to use the new profiles.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2021-11-15 09:11
@guennid We found issues with the last version I gave you to test, so can you please test with DisplayMagician v2.1.0.239 instead? 
[DisplayMagicianSetup-v2.1.0.239.zip](https://github.com/terrymacdonald/DisplayMagician/files/7537345/DisplayMagicianSetup-v2.1.0.239.zip)


Thanks
Terry

**Comment by guennid** [comment] 2021-11-15 15:39
Hi Terry,
sorry for my late response. Was a little bit busy.

I will test the new version. 
What i found out with your last version: The Taskbar just appears on top for a few times. Then i used the old display manager "helios". After done this the taskbar is every time on the bottom. But now i get the issue that the taskbar isnt set correctly to the main window. But i will test this this evening with your new version. I will come back accordingly.

Günter

**Comment by guennid** [comment] 2021-11-15 15:47
I installed your new version, but i get an error at starting:
Translated from german : The value cant be zero Paramtername: first

After confirming this error the App wont start, and i have to killl  it via Taskmanager

**Comment by guennid** [comment] 2021-11-15 15:53
I tried the old links for changing the display, these still works. Dont geht the top taskbar, but still the issue with the "Main" Screen. To explain:  After switching back to triple the taskbar is on all screens, but the Main Window Taskbar is on the left screen. If i look in the window Display settings the main screen is still the middle one. If i change it to left and the back to middle, the taskbar changes correct to the middle as main screen.

**Comment by terrymacdonald** [comment] 2021-11-15 19:02
Hi Günter,

DisplayMagician v2 uses 3 brand new video control libraries that I've
written myself. I made the change so that I could get all the other
settings like HDR, and custom colour settings from the NVIDIA cards, and so
I could support AMD Eyefinity.

This was such a major change that is taken many months to get this bugs
sorted out. I'm now at a point that most of the configuration works, but I
have a person's who still has some issues when they swap from a surround
display profile back to a non-surround profile. When they do that, the
non-surround profile only partly gets applied.

I was hoping you would be able to test that for me when you are testing the
windows taskbar.

Thanks
Terry

**Comment by Mobeeuz** [comment] 2021-11-15 19:48
Had an issue with 239
![image](https://user-images.githubusercontent.com/33134962/141844542-76a539ce-4558-4d1f-82ee-f5e2b4f0f008.png)

Display Magician will no longer start

**Comment by terrymacdonald** [comment] 2021-11-15 20:32
@Mobeeuz Anyone currently running 1.1.4 or 2.0.1 will get prompted for replacing the profiles as they changed. Anyone running the 2.1.0.X test builds won't be prompted to recreate the configs. It is a good point though that I should be telling all my testers this...

Sorry!
Terry

**Comment by guennid** [comment] 2021-11-16 08:06
@terrymacdonald 
Just tested again the new version with clean configs.
The Taskbar wont be moved to the top of the screen, but i have still the issue with the mainscreen option.
Screenshot:
![image](https://user-images.githubusercontent.com/11660551/141945152-e55109c4-1ac8-4918-ab2c-c74932bdcc61.png)

The windows settings are telling me, the middle screen is the main screen. But that taskbar is in mainscreen mode on the left display.
If i change the setting to left Display and then back to middle, the taskbar changes like it should.  After changing to surround and back to normal display, the same happens again.

**Comment by terrymacdonald** [comment] 2021-11-16 18:30
Can you also please fill this list out of your current setup:

Windows Version: Win11 Home?
DisplayMagician Version: 2.1.0.239
Video Card: [e.g. Asus NVIDIA GTX1070]
Number and make/model of monitors: [e.g. 2xDell UH2718H, 1x LG G27U17D]
Date of last video driver update: [e.g. 2021-02-15]
Date of last windows update: [e.g. 2021-02-15]

That will also give me some more information with which to troubleshoot.

Also, I didn't realise that you had moved the windows taskbar from the bottom of the screen to the top of the same screen. I thought you meant you had a 4 screen layout with and additional screen on top!. Now I think I have a better understanding of your issue.

I have never tested whether DisplayMagician can track the taskbar location on the screen. My understanding is that the taskbar location is a completely different thing to control. It will require me to investigate how to control that and to add the settings. I think it is a good idea to add that functionality, but it will be a little while to support out how to do that.

The failure to move the main display is a big worry though. I have another person with a similar problem, and they have a RTX 3080. Do you have the same model video card?

To test if that is a problem, can you please download and run NVIDIAInfo v1.2.5b from here: [NVIDIAInfo-v1.2.5b.zip](https://github.com/terrymacdonald/DisplayMagician/files/7543583/NVIDIAInfo-v1.2.5b.zip)

NVIDIAInfo is a little test program that uses the same video libraries as DisplayMagician, and I use it to test the display changing functions.

## To setup this software:

- Firstly, set up your display configuration using NVIDIA settings and the Windows Display settings exactly as you want to use them (e.g. one single NVIDIA Surround window using 3 screens)
- Next, save the settings you currently are using to a file to use later, using a command like `NVIDIAInfo save triple-surround-on.cfg`
- Next, change your display configuration using NVIDIA settings and the Windows Display settings to another display configuration you'd like to have (e.g. 3 single screens without using NVIDIA Surround)
- Next, save those settings to a different file to use later, using a command like `NVIDIAInfo save triple-screen.cfg`

## To swap between different display setups:

Now that you've set up the different display configurations, you can swap between them using a command like this:

- To load the triple screen setup using NVIDIA surround: `NVIDIAInfo load triple-surround-on.cfg`
- To load the triple screen without NVIDIA surround: `NVIDIAInfo load triple-screen.cfg`

Please swap between surround and triple screen, and see if it swaps without any error. If you get an worry, please upload the 2 .cfg files and the NVIDIAInfo.log files from when the error happened.

Hear from you soon.
Terry

**Comment by terrymacdonald** [comment] 2021-11-17 05:02
@guennid I also did some research on taskbars in Windows 11, and it appears that Windows 11 doesn't allow you to move the taskbar at all: https://www.tomshardware.com/how-to/windows-11-taskbar-move-to-top. The previous code that others used to adjust the taskbar doesn't work any longer. I tried to create some code that used that older technology and it just didn't work. It appears the older SHAppBarMessage tricks don't work now.

Microsoft doesn't support moving the Windows 11 taskbar natively at all any longer. As such there is no way to add that functionality in Windows 11 through an API. 

I'm not sure if the windows taskbar moving to the top of the screen is an NVIDIA bug, or something odd with windows 11 at the moment. I'm just using the native display commands in the NVIDIA driver and the native display commands in the windows CCD and GDI APIs to change the screen displays. I'm not recording or changing the taskbar positions at all. 

There is basically nothing I can do at present I'm sorry. I'm not sure its a DisplayMagician bug, or one with the NVIDIA driver, but in any case it's not something I can fix :(. 

I'm going to close this issue, and assign it with cantfix.

Thanks
Terry

**Closed by terrymacdonald** 2021-11-17 05:02 UTC
Labels: bug

**Comment by terrymacdonald** [comment] 2021-11-17 05:39
@guennid One question I still have... do you have one taskbar only on your primary display, or do you have it set so there are taskbars on each display? I haven't tested with only one taskbar on one screen. I'll do that now.

**Comment by terrymacdonald** [comment] 2021-11-17 06:43
The taskbar moves around with the primary screen when only one taskbar is set in the taskbar settings, as it should do. Just tested.

**Comment by guennid** [comment] 2021-11-18 18:40
Hi Terry,

i have the taskbar on all screens. I am wondered about this problem also. Let us keep this ticket closed and i will investigate a few things in Windows 11 with the task bar. 
Thanks for your help.
