### ISSUE TITLE
Switching between 3,4, and 6 monitor profiles - maximum displays attached to DisplayPort exceeded.

### ISSUE THREAD

**Issue by e-wan-o** [terrymacdonald/DisplayMagician#186] opened 2023-01-24 16:07 UTC
**Describe the bug**
I have 6 screens connected which can be configured and function correctly using windows display settings.

I've created 3x profiles using the GUI (3, 4 & 6 monitors).

Manually extending or disconnecting a screen at a time via windows display settings seems to work correctly, but switching profiles a few times using DisplayMagician seems to cause a problem reported by AMD drivers:

Error:
The maximum number of displays that can be supported per DisplayPort connector has been exceeded. To use the display you just plugged in, first disconnect another display or move the current display to another connector.

Using DisplayMagician to try to apply profiles after this error results in no further changed applied.

I've encountered similar problems using monitor-profile-switcher detailed here:

https://github.com/cooolinho/monitor-profile-switcher/issues/2

**To Reproduce**

Boot PC with DisplayMagician loaded.
Switch to alternate profile - success.
Subsequent profile switches increase the chance of an error reported by the AMD driver.

Once the error is triggered, a reboot seems to reset things and profiles can be applied again using DisplayMagician until the error message is displayed again.

**Expected behaviour**
Multiple changes of profile during one login session without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/75482178/214342471-b9cb257b-a5d6-4db4-a17c-0c45b2838957.png)

**Reporting Logs**

[DisplayMagician-Support-20230124-2038.zip](https://github.com/terrymacdonald/DisplayMagician/files/10493835/DisplayMagician-Support-20230124-2038.zip)

**Enviroment (please complete the following information):**

 - Windows 10 Home: Build 19045.2486
 - DisplayMagician Version 2.5.0.352
 - Video Card: AMD Radeon RX580
 - Number and make/model of monitors: 6 monitors total.
 - 1x LG UltraGear 27GL850 connected directly to the card - DP
 - 1x Dell P2219H connected directly to the card - DP
 - 1x DP MST Hub (Club3D) connected directly to the card - DP
 - 1x Dell P2219H connected to the MST Hub - DP
 - 3x Dell U2211H connected to the MST Hub - DP
 - Date of last video driver update: 30/11/2022 (Adrenalin 22.11.2)
 - Date of last windows update: ‎12/‎01/‎2023

**Comment by terrymacdonald** [comment] 2023-01-24 20:05
Hi,

Unfortunately I don't think there is anything I'll be able to do about
this. DisplayMagician asks the AMD driver for a copy of it's configuration,
and then stores that sell for later use. When you go to apply a display
profile, DisplayMagician gives that same configuration back to the AMD
driver.

Effectively, the AMD driver API doesn't like it's own configuration...
which is not good.

There is likely nothing we can do about this; it's ultimately up to AMD to
fix this restriction. My guess is that the AMD ADL driver has some
restriction on the maximum number of screens and doesn't take into account
the use of an MST hub by a customer.

You could try logging a case with AMD directly?

An alternative that may work for you, is using my CCDInfo CLI software:
https://github.com/terrymacdonald/CCDInfo

That software was designed for testing just the WinLibrary that I
developed. It doesn't use the AMD ADL driver at all, which means it could
avoid the error you are getting. Please note that CCDInfo cannot do AMD
Eyefinity at all because it doesn't use the AMD driver, but as long as you
don't need AMD Eyefinity then it might work for you.

You can then save each display layout to different configuration files and
then create separate PowerShell files on your desktop to load each
configuration. This would allow you to get around the issue.

Hope that helps!

Thanks
Terry

**Comment by e-wan-o** [comment] 2023-01-24 20:36
Thanks for the fast response and the information, I also suspected a driver issue - but thought I better raise it as an issue in case it was something concerning the method by which you call for a profile to be applied.

My suspicion is that when a profile is applied, the driver uses a counter for screen enumeration - which is cycled through till an upper limit is reached. It might be that I've just not reached it while manually disconecting and extending 1 screen at a time (it's a slow process, and I'm impatient). I also wonder if the MST and all screens attached are treated as a block, so when and update happens to one screen attached to the MST, it's actually using 4/5 counts of the maximum display counter. 

I don't think I use Eyefinity (in the sense of creating groups of monitors). I just connect the screens and drive them independently as 6 independent screens. I'll give CCDInfo a go and see if it behaves differently - if it does maybe it could be incorporated into the GUI system as alternative method for switching profiles?

I'll report back with my testing and complete the bug report with log files for completeness.

**Comment by terrymacdonald** [comment] 2023-01-24 21:24
@e-wan-o I did a little digging, and found this for someone who also had a problem with a RX 580 card and 6 monitors: https://linustechtips.com/topic/1049519-need-help-setting-up-6-monitors-on-rx-580/

"Solved: I finally found a setting in the Radeon control panel that had set crossfire set to on. When I disabled crossifre it immediately recognized all of the additional screens. Thanks everyone for the help!"

Maybe try turning off Crossfire if it is on?

Regarding CCDInfo - DisplayMagician uses WinLibrary, AMDLibrary and NVIDIALibrary libraries. They were all developed by me and use the Windows CCD API, AMD ADL and NVIDIA NvAPI respectively. When DisplayMagician detects and AMD card, it uses **both** WinLIbrary and AMDLibrary to store settings - that's because each driver has different settings, and to make sure things are set correctly I need to grab all of the settings that may be applied.

CCDInfo was specifically made to test WinLibrary functionality independently, which is why it only contains the Windows CCD API calls. It is alsoi why it may help in your case, as it avoids calling the AMDLibrary (which doesn't work in your specific use case). Hope that clarifies.

I'll go ahead and close this case as I can't fix it myself, but please keep me up to date with what you find. If AMD makes a driver change in the future I'd like to figure out if there is anything I need to do to get the 6 screens working for you.

Thanks
Terry

**Closed by terrymacdonald** 2023-01-24 21:24 UTC
Labels: bug, cant fix

**Comment by e-wan-o** [comment] 2023-01-29 21:08
Hi Terry,

I finally managed to get some time to come back and update this (mainly for completeness sake for others following in my footsteps), but here I am!

I tried using CCDInfo to save profiles for 3 and 6 monitors, and encountered the same bug when switching between profiles.

I think this is clearly a driver bug, and suspect the next step would be to contact AMD to raise a bug with them. Any info pointing me in the correct direction would be appreciated.

At some point in the next few months I'm planning on running some linux based distro (probably Arch) with either i3 and/or sway as the mindow manager on the same hardware. If you are interested in how monitor configuration changes are handled under that environment I can update here with my experiences - although it might be outside the scope of your interest with this being a M$ only project.

To respond to your suggestion of turning Crossfire off, I think this is a bit of a red herring. Firstly in my case I onl;y have one card in the system, so crossfire is not activated in the driver (hence not a visible option in the driver control centre). The thread you were refering to describes turning off Crossfire when two cards are installed to allow the both cards to drive monitors. When running in crossfire mode the primary card is the only card that can drive monitors because the secondary card(s) is acting as a processing unit only - and display outputs are limited to the primary card only. I don't think this has anything to do with the bug I am encountering.

For the moment I'm going to continue to use DisplayMagician for profile switching and see if AMD can provide a fix at some point.
