### ISSUE TITLE
DisplayMagician won't start 2.3.1.60

### ISSUE THREAD

**Issue by Dogy007** [terrymacdonald/DisplayMagician#104] opened 2022-05-07 21:31 UTC
**Describe the bug**
Application won't start. Installed multiple times.
It also doesn't start if I upgrade from 2.1.5.5
If a Profile from version 2.1.5.5 exisits, the banner with the "you need to recreate your profiles" will show up, if no profile exists, nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
Install Application, try to start. no process will appear and the application won't show up in any way

**Expected behaviour**
Application opens up

**Reporting Logs**

If DisplayMagician does not:
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- [DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/8645955/DisplayMagician.log)
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json`  (empty folder)
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json` (empty folder)
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`
  - [Settings_2.0.json.log](https://github.com/terrymacdonald/DisplayMagician/files/8645958/Settings_2.0.json.log) (renamed to .log since json is not supported on github)

**Enviroment (please complete the following information):**
 - Windows Version: Win11 21H2
 - DisplayMagician Version 2.3.1.60
 - Video Card: NVIDIA 3080 TI
 - Number and make/model of monitors: 3x ASUS TUF Gaming VG27AQ1A(Connected but disabled in nvidia control panel) 1x Samsung Odyssey Neo G9 G95NA (Connected via HDMI & Displayport in 2 monitor mode [PIP])  
 - Date of last video driver update: 26.04.2022 (Driver 5.12.59)
 - Date of last windows update: 07.05.2022 (Today)

**Additional context**
Shortcuts get created (rightclicking on Desktop will show the "change display profiles button" nothing happens if I try to create a new profile there either

**Comment by terrymacdonald** [comment] 2022-05-08 04:54
Hmmmm. I'd like to try with completely blank settings again just to test
it out. To do this, can you please first course DisplayMagician.

Next, try renaming your old
C:\Users\<username>\AppData\Local\DisplayMagician folder to something
like C:\Users\<username>\AppData\Local\DisplayMagicianOld.

Then start DisplayMagician v2.3.1.60 again fresh, and see if it starts. If
it does, please create your display profiles and see if you can
successfully change between them.

Then report back here with the results of your testing.

I've got a gut feeling that DisplayMagician may not like your DP and HDMI
dual-connected Samsung display, but we'll see what the testing shows. I'll
also take a look at the log file when I get time over the next two days and
see what it shows.

Thanks
Terry

**Comment by Dogy007** [comment] 2022-05-08 15:52
Hey Terry

I just tried your suggestion. A new folder appered, but it still wont start.

The log looks still the same, but I uploaded it anyways. Version 2.1.5.5 will start, I tested this yesterday, just the newer version doesn't like my setup as it seems
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/8647306/DisplayMagician.log)
.

**Comment by terrymacdonald** [comment] 2022-05-14 09:29
@Dogy007 So I've looked at your logs, and they are so very weird. You get an issue at the part of the loading process where the WinLibrary part of DisplayMagician attempts to get the location of the Windows Taskbar. It errors when it tries.

This is unusual. I'm not actually sure why it's causing an exception there. I will have to do some hunting through the code and see if there is a potential error that could be triggering on your computer. It is very strange though!

Do you run as an admin on your computer? Or did you install DisplayMagician and allow the installer to have admin rights? I wonder if it is a permissions issue. I'll have a dig through the code and see if there is an issue.

Thanks
Terry

**Comment by Dogy007** [comment] 2022-05-14 09:43
I run as admin. Since you mentioned problems with the taskbar, i have the software startallback running on win 11, maybe there is a conflict. I try to disable it later today to see if it makes any difference

**Comment by Dogy007** [comment] 2022-05-14 18:34
Hey!

After I disabled startallback's taskbar imrpovement and tried a few times (It still failed to start 4 or 5 times) it finally started. Just before I had success with starting it, I changed my monitor from pip to Single monitor and then back again. I am not sure if I will be able to start it without problems after a reboot. I keep you posted.

Thanks 
Dogy

**Comment by terrymacdonald** [comment] 2022-05-14 18:39
Interesting! Can you please create a Support ZIP File when you do get it to
start and upload it to this issue? It might give me a tip on what's going
wrong. I might be able to work around the changes that program makes.

You can create a Support ZIP File by going into the settings window from
the main DisplayMagician window, then clicking the Create Support ZIP File
button.

Thanks
Terry

**Comment by Dogy007** [comment] 2022-05-14 21:03
[DisplayMagician-Support-20220514-2123.zip](https://github.com/terrymacdonald/DisplayMagician/files/8693866/DisplayMagician-Support-20220514-2123.zip)
Voila :)

**Comment by terrymacdonald** [comment] 2022-05-17 22:07
@Dogy007 did a reboot make DisplayMagician start more reliably?

**Comment by Dogy007** [comment] 2022-05-18 21:17
I left the startallback taskbar improvement disabled, since then it starts reliably. I'm just fighting with other problems (Software is unresponsive after screen profile switch and needs to be restarted every time. I guess it really doesn't like my setup. 

I also can't reliably change screen profiles (all 5 screens just flicker for 5 - 10 seconds and refuse to accept their profiles. 

I guess we can close this issue, since the "won't start" problem is solved by disabling startallback.

**Comment by terrymacdonald** [comment] 2022-05-18 21:32
We could  change this issue to try and debug the screen changing issue if
you would like. It sounds like it could be a NVIDIALibrary error. I have
some software called NVIDIAInfo that is specifically designed to test the
NVIDIALibrary outside of DisplayMagicain. That is really useful for finding
profile issues like the ones you're describing.

Are you interested in changing this issue to be a profile problem and
trying to debug it?

Thanks
*Terry *

**Comment by Dogy007** [comment] 2022-05-18 21:50
Of course I would be interested If it could possibly help me and others with the same problems.

**Comment by terrymacdonald** [comment] 2022-05-25 07:19
@Dogy007 that result is quite weird. The fact it never 'equals' a config after loading the config indicates to me that something strange is happening. It should match directly after saving a config, but it isn't. 

All of the 3 different configs appear to have applied correctly. So that says that they are at least being parsed and processed by Windows. Can you please confirm that all the display layouts looked correct in Windows Settings? If you didn't look, can you please run the 'NVIDIAInfo load ...' commands in that last set of instructions I gave you, and please have a look to make sure that your display layout is changing correctly after each load command? I'm trying to figure out if it is a problem with applying a config, or testing the equality of the config.

Additionally, the triple.cfg and triple-reload.cfg are VERY similar in structure, but there are a few odd differences. There are the differences I expect, like the reordering of the DISPLAY2 and DISPLAY3 in the Windows section, and the changing of the display mode IDs. But there are a few changes that I don't expect, like the fact that the GDI X and Y coordinates for the screens change as they change sides, and the order of the taskbars in the taskbar layout is reversed too.

It *could* be those last two things that are throwing the equality testing, so I'd have another look at the code and see if there is anything I can do to loosen that check or accommodate for those changes.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-05-25 07:30
@Dogy007 I've found something that may have affected the equality testing. Can you please perform the instructions below with NVIDIAInfo v1.7.4b uploaded here:
[NVIDIAInfo-v1.7.4b.zip](https://github.com/terrymacdonald/DisplayMagician/files/8768873/NVIDIAInfo-v1.7.4b.zip)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `NVIDIAInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Next swap back to the cloned screen display layout again:
- Load the second windows display as `NVIDIAInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save cloned-reload.cfg`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)
 
And please also copy the Powershell window and paste it into a text file.

Then please zip up all the files generated above, and we'll see if there is anything useful in there (hopefully it works now with 1.7.4b!)

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-05-28 09:13
@Dogy007 I found some errors with the file upgrade logic that would have caused your original file upgrade issue. I've now fixed that so it shouldn't happen for other users. I also have made it so it will now use the settings file correctly.

There was a bug that meant that DisplayMagician was wanting to read and write from 'Settings_2.4.json', but the upgrade logic only created 'Settings_2.0.json', so the settings weren't used properly. This is now fixed.

And lastly, the ProgramSettings object kept loading and saving with every single change and even during load. This made it way more likely some file IO lag would delay DisplayMagician responsiveness. This has all been fixed and should work much faster now.

Thanks @Dogy007 for pointing me in the direction of that broken code, as it was WAY more broken that I thought it was. Once I started poking around that area it was obvious it needed some serious work on it. That has been done now, so it will all come out in the next 2.3.2 which will be released in a week or two. All your problems should go away then (hopefully!) :).

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-05-28 09:14
Oh I forgot to mention. As it *should* be fixed now, I will close your issue. If it turns out that the problem is still happening when you upgrade to DisplayMagician v2.3.2, then please reopen this issue and we'll try working on it again.

Thanks
Terry

**Closed by terrymacdonald** 2022-05-28 09:14 UTC
Labels: bug
