### ISSUE TITLE
2 GPUs conflicting

### ISSUE THREAD

**Issue by UppGRayeDD1337PMP** [terrymacdonald/DisplayMagician#191] opened 2023-02-03 13:15 UTC
Hi,

I have 5 monitors, where 4 are connected to a Radeon GPU, and one to the Nvidia. In previous versions I was able to use Display Magician only wit the Radeon and manually enabling the monitor on the Nvidia when I needed. However, in the new version the software defaults to Nvidia and I can't save any display configuration in teh radeon GPU.

Is there a fix for this? I tried everything I could to trick it to work with no luck.

**Comment by terrymacdonald** [comment] 2023-02-09 07:38
Hi @UppGRayeDD1337PMP,

DisplayMagician always tried NVIDIA cards before AMD cards before all other cards, as this was how it was designed. The original theory was that no-one would have both cards in a single PC, and I wanted to ensure that the configs were kept separate so that they didn't interfere with each other.  This first theory has been proven to be wrong, as there is a small percentage of people with two different cards in there, and that needs DisplayMagician to work differently.

The way I architected DisplayMagician was that it worked in 3 different 'modes':
- NVIDIA mode means that it looks for NVIDIA cards and the NvAPI driver dll, and if it finds both it then checks for NVIDIA Surround settings (and other NVIDIA settings) and also grabs all the Windows settings so that it can find all attached screens.
- AMD mode means that it looks for AMD cards and the AMD ADL  driver dll, and if it finds both it then checks for AMD Eyefinity settings (and other Amd settings) and also grabs all the Windows settings so that it can find all attached screens.
- Windows mode means that it just grabs all the Windows settings so that it can find all attached screens.

DisplayMagician by default attempts to figure out the best mode to use, by trying NVIDIA first, then AMD if NVIDIA mode doesn't work, and then finally Windows mode if neither NVIDIA or AMD mode works. You can override that default behaviour by running `DisplayMagician.exe --force-video-library AMD` to force AMD mode, `DisplayMagician.exe --force-video-library NVIDIA` to force NVIDIA mode, and `DisplayMagician.exe --force-video-library Windows` to force Windows-only mode.

Windows-only mode may work better for you to get all screens and all GPUs to be scanned, so maybe you could try `DisplayMagician.exe --force-video-library Windows` to force Windows-only mode.  Keep in mind that the Windows-only mode will mean that neither AMD Eyefinity or NVIDIA Surround can be used whjile DisplayMagician is running in that mode.

Unfortunately this won't be fixed until DisplayMagician v3.0.0 is released. I am rewriting a huge chunk of DisplayMagician as part of that work, and I plan on eliminating the idea of video library 'modes', which should hopefully alleviate the issues you describe above.

Can you please try running DisplayMagician in Windows-only mode and then see if you still have issues? Please go into The DisplayMagician Settings and make sure that your Log Level is set to TRACE, and then create a couple of temporary test Display Profiles. Try to swap between those temporary Display Profiles, ant then go back to the DisplayMagician Settings window and create a Support ZIP File. Please upload the Support ZIP File here using your web browser, and then I'll take a look at it.

At a glance, this issue does seem similar to #187. 

Thanks
Terry

**Comment by UppGRayeDD1337PMP** [comment] 2023-02-20 03:20
Hi Terry,

Thanks for your help. I've done a lot of testing in the past week (I have a
faulty adaptor that plays up) and realized that when I force the app to run
using AMD drivers, It can  save and switch between profiles that use both
GPUs or only one. I haven't tried eyefinity yet. But I tried every
combination possible between the monitors and it worked almost perfectly.

The Only issue I have is when I restart, most of the time I have to
reconfigure everything again. I am not sure if this is the faulty adaptor
or the app.

Also, It didn't work at all forcing Windows drivers. The app fails to load
and when it does, anything I try gives me a windows error message.

See the log attached.

Some specs of my system so it help you if needed:

Nvidia - HDMI - Phillips 1080p cheap one
AMD - USB c to DP adaptor - Gigabyte FI32q-x
AMD - DP - Gigabyte FI32q-x
AMD - DP - Gigabyte FI32q-x
AMD - DP - Samsung TV

I am using 5 meters cables to each one and there's A LOT of EMI all over
and I am using the best shielded cable I can find.

AMD Adrenalin 22.11.2 - GPU overlcoked- Asus 6800XT LC
Nvidia  474.14 - GT730 - I only use it to power the HDMI to the 1080p
monitor

Windows 11 Pro - 10.0.22621

I think my user case is the worst case scenario for your tests, since I
have a mix of HDR, HZ, resolution, drivers, etc... And my profiles often
use different main monitors and settings (HZ and HDR) config using the same
or different monitors depending on what I am doing with the monitors.

My go to profiles are:

1 - Samsung 42" Tv - Main monitor
2- Quad monitor for racing - 1x Phillips27" 70hz on Nvidia + 3x
***@***.*** 1440p
3- Triple monitor for racing - 3x ***@***.*** 1440p
4- Triple monitor for racing - 3x ***@***.*** 1440pin eyefinity (rarely
used)
5- All monitors on for multiple uses, rarely used.


Give me a shout if you need anything else and thanks for the great app.

**Comment by terrymacdonald** [comment] 2023-02-20 04:10
Woah, that does indeed sound like the most tricky setup I think I've heard
so far.

Forgive me, but I didn't quite understand whether it was working now with
the DisplayMagician.exe --force-video-library AMD command. Are you saying
that with the AMD command-line parameter it works properly now?

Thanks for finding a multi-GPU bug in the Windows only code. Unfortunately
Github eats any attachments in email replies, so can you please visit the
Github issue through your web browser and then upload it through the Github
web interface? You can do that here:
https://github.com/terrymacdonald/DisplayMagician/issues/191

Thanks

*Terry *

**Comment by UppGRayeDD1337PMP** [comment] 2023-02-20 05:00
Hwere you go...

So, With forced AMD library it looks like it is working with anything I tried, but when I restart my PC, sometimes the profiles stops working, as if I plugged/unplugged a monitor. I am not sure if this is due to a possible faulty DP adaptor, EMI interference that plages my PC or something with the app. Unfortunately, I couldn't troubleshoot this.

But I find interesting that with forced AMD I can control the nivida monitor as if it was connected in the AMD GPU. I couldn't do this in previous versions, about 3 months ago.

[DisplayMagician-Support-20230220-1402.zip](https://github.com/terrymacdonald/DisplayMagician/files/10779727/DisplayMagician-Support-20230220-1402.zip)

**Comment by terrymacdonald** [comment] 2023-02-20 05:39
Yeah, IIRC I changed some display logic in 2.5.1.350 that fixed the multi
GPU support. It was in there beforehand, but I hadn't correctly implemented
it and there were some logic flaws that stopped it working.

With Version 3.0.0 I'm taking the opportunity to try to get it working
without the need for 'modes'. This is going to take a little bit of
development to get sorted, and v3 is already going to be a lot of work to
get right. I may call on your help for testing the combined video libraries
when I finally get them done. It's going to be 3-6 months away as there is
just so much to do :(

As for the profile not working after a reboot, that *may* be related to the
USB adapter, but it's hard to say. USB is a dark art, and USB video is even
worse. I've not had enough users with it to know what happens to the USB
identifiers after reboots. I have a sneaking suspicion that the USB ID
changes somehow between reboots on some devices, but I don't have a USB
monitor to test with so I can't be sure. So at this stage I think I'll roll
that testing in with the combined video libraries v3 work I mentioned above.

Thanks
*Terry *

**Comment by terrymacdonald** [comment] 2023-03-03 21:09
@UppGRayeDD1337PMP is this force AMD library workaround ok for now? Are you ok for me to close this issue? I'll keep your issues in mind with the work on DM v3.0, and I will definitely get you to do some testing with the combined video library when it's finished.

Thanks
Terry

**Comment by UppGRayeDD1337PMP** [comment] 2023-03-05 04:18
Hi Terry,

Yes, it works fine. Thank you

**Comment by terrymacdonald** [comment] 2023-04-11 03:03
Closing this issue as the bug has a workaround, and the issue is in the development list of tasks to be fixed in v3.0.0.

**Closed by terrymacdonald** 2023-04-11 03:03 UTC
Labels: bug, workaround
