### ISSUE TITLE
Switching Nvidia Surround OFF doesn't work (same problem with versions 1.1.4, 2.1.5.5 and 2.2.0.52)

### ISSUE THREAD

**Issue by HS34** [terrymacdonald/DisplayMagician#83] opened 2022-01-24 20:53 UTC
**Describe the bug**
While in surround, applying a "not surround" profile fails with no error.
I'm not sure what the difference is with issue #76, but since Terry asked me to log this as a new issue...
[https://github.com/terrymacdonald/DisplayMagician/issues/76](url)
 
**To Reproduce**
created profile "3 screens only"
created profile "4 screens"
created profile "surround"
Failed to apply profile "3 screens only"
Failed to apply profile "4 screens"

**Screenshots**
![image](https://user-images.githubusercontent.com/24624829/150859968-a0dd930f-35af-4c25-a479-f4521ec7bcb7.png)

**Reporting Logs**
Logs with Display Magician 2.2.0.52 : 
[DisplayMagician-Support-20220124-2051.zip](https://github.com/terrymacdonald/DisplayMagician/files/7928692/DisplayMagician-Support-20220124-2051.zip)

Logs with Display Magician 2.1.5.5 :
[DisplayMagician-Support-20220124-2120.zip](https://github.com/terrymacdonald/DisplayMagician/files/7928694/DisplayMagician-Support-20220124-2120.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win 10 21H2
 - DisplayMagician Version [2.1.5.5]
 - Video Card: [2x TitanX (pascal)]
 - Number and make/model of monitors: [3x Asus VG278H + LG 55C9]
 - NVidia Driver : 452.06

**Additional context**
I've checked with versions 1.1.4, 2.1.5.5 and 2.2.0.52.
Most of the time I can apply profiles as long as I don't switch OFF surround.

I'm pretty sure it worked with version 1.1.4 sometimes ago, I think before I updated my windows 10 to version 21h2 (or maybe even before 21h1).

My NVidia Driver is still 452.06 and I will stick to it as long as I can because it's the last driver compatible with 3DVision in DX11.
So my driver version has not changed for a long time. That's why I wonder if windows hasn't change something in updates.

I've got 4 screens connected on 2 TitanX (pascal) : 3x 3DVision Asus screens (for surround) + my TV (HDR enabled on the TV)
When I enable or disable surround using nvidia control panel, my PC sometimes crashes, stucked with black screens. HeliosDisplayManagement and DisplayMagician worked far better (at least for a time). Congratulations again for doing better than the manufacturer !

Here is what I've checked :

-----------------------------------------
Display Magician 1.1.4
-----------------------------------------
created profile "3 screens only"
created profile "4 screens"
created profile "surround"
Failed to apply profile "3 screens only"
Failed to apply profile "4 screens"

I disabled surround in nvidia configuration panel and set "activate all screens" : the positions of my screens were not correct
Success applying profile "3 screens only" : the positions of my screens are now OK
Failed to apply profile "4 screens"
Failed to apply profile "surround"

-----------------------------------------
Display Magician 2.2.0.52
-----------------------------------------
created profile "3 screens only"
created profile "4 screens"
Failed to apply profile "3 screens only"

created profile "surround"
Failed to apply profile "3 screens only"
Failed to apply profile "4 screens"

created profile "SLI optimise performances on 1 screen"
Failed to apply profile "3 screens only"
Failed to apply profile "4 screens"
Failed to apply profile "surround"

I disabled SLI in nvidia configuration panel and set "activate all screens" : the positions of my screens were not correct
Failed to apply profile "3 screens only"
Success applying profile "4 screens" : the positions of my screens are now OK
Failed to apply profile "surround"

Regards,

From @terrymacdonald  :
> Hi @HS34 Could you please log this as a new issue? It sounds like it's a slightly different problem. Please make sure that you try and make it fail, and then without closing DisplayMagician can you please ZIP up your C:\Users\<username>\AppData\Local\DisplayMagician\ folder, and then upload it to the new issue that you create. That will give me some log entries to review, and will show me what could be wrong. Please also tell me if you have tried v2.1.5 of DisplayMagician at all. If be very interested to see if you have the same problem with the v2.x series of DisplayMagician as you do with the V1.1.4. It could a absolutely be a windows change affecting your system (and us too}, but it will be very difficult to know that. The fact that v1.1.4 works for @sk666 and @FormelLMS when the 2.x series doesn't shows me that there is something in the way the 2.x works that doesn't work. The fact that v1.1.4 does work for them means that it's likely a rare bug in my NVIDIALibrary custom video library. Thanks Terry
>

----------------------------------------------------------------------------------
Second round of tests (logs attached)
----------------------------------------------------------------------------------
-----------------------------------------------
Display Magician 2.2.0.52
-----------------------------------------------
Active profile : "4 screens"
Success applying profile "surround" : TV disabled, 3 Asus screens in surround
20:49 : Failed to apply profile "3 screens only". Nothing happens.
20:50 : Failed to apply profile "4 screens". Nothing happens.
[DisplayMagician-Support-20220124-2051.zip](https://github.com/terrymacdonald/DisplayMagician/files/7928692/DisplayMagician-Support-20220124-2051.zip)

-----------------------------------------------
Display Magician 2.1.5.5
-----------------------------------------------
created profile "surround 2.1.5.5"
created profile "4 screens 2.1.5.5"
created profile "3 screens only"
Success applying profile "4 screens"
Success applying profile "surround 2.1.5.5"
21:19 : Failed to apply profile "4 screens". Nothing happens.
21:20 : Failed to apply profile "3 screens only". Nothing happens.
[DisplayMagician-Support-20220124-2120.zip](https://github.com/terrymacdonald/DisplayMagician/files/7928694/DisplayMagician-Support-20220124-2120.zip)

**Comment by terrymacdonald** [comment] 2022-01-24 21:26
Thanks for testing that @HS34. I'll have a look at the logs after work
today and see what I can find in there.

I've a feeling we'll need to move to testing the underlying NVIDIALibrary
display library I wrote to see where we can fix things, but I'll confirm
over the next few days.

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com

**Comment by terrymacdonald** [comment] 2022-01-28 03:47
@HS34, some amazingly great news! After a LOT of work I've finally cracked the problem of how to disable Mosaic/Surround without using disabling the NvAPI_Mosaic_EnableCurrentTopo (which is what I believe is causing your issues). Turns out that with some clever processing I can convert the existing Mosaic grid topology to a series of single screen grid topologies using NvAPI_Mosaic_SetDisplayGrids, and the NVIDIA Driver will disable Mosaic/Surround!

I have also engineered it that if the NvAPI_Mosaic_SetDisplayGrids fails to work, it will revert to using NvAPI_Mosaic_EnableCurrentTopo instead. This now make the mosaic disabling much more robust 👍 

So, can you please both download and extract the attached NVIDIAInfo v1.5.0 into a folder, and then perform the following tests for me. Make sure you do every step in order, and record the results. We use NVIDIAInfo to specifically test the NVIDIALibrary updates that I just made, so I can check they worked before I add the new library updates back to DisplayMagician.

[NVIDIAInfo-v1.5.0.zip](https://github.com/terrymacdonald/DisplayMagician/files/7955519/NVIDIAInfo-v1.5.0.zip)

- Open a command line/powershell to that same folder you extracted NVIDIAInfo-v1.5.0.zip
- Delete the log files from the previous tests: `del *.log`
- Delete the cfg files from the previous tests: `del *.cfg`
- Set up a new Regular profile setup, and then run `NVIDIAInfo save regular.cfg`. That will save the Regular configuration (non-surround)
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
- Test that the Regular configuration was saved correctly by `NVIDIAInfo equal regular.cfg`. Please record if this test was equal or not. We want it to be equal.

That's the regular config saved. Next we want to create a new surround config.

- Set up your Surround profile setup using NVIDIA Control Panel, and then run `NVIDIAInfo save surround.cfg`. That will save the Surround configuration
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Test that the Surround configuration was saved correctly by `NVIDIAInfo equal surround.cfg`. Please record if this test was equal or not. We want it to be equal.

At this stage we have the two basic configs set. Next step is to see if changing between the display profiles works:

- Change from the Surround profile to the Regular profile by running `NVIDIAInfo load regular.cfg`. That will try to swap to the Regular configuration.
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-load.log"`
- Save the current profile by running `NVIDIAInfo save regular-applied.cfg`. That will save whatever the config is now, so I can compare it against what we want it to be.
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-applied.log"`
- Test that the configuration no longer matches the Surround profile by running `NVIDIAInfo equal surround.cfg`. Please record if this test was equal or not. We want it to NOT be equal.
- Test that the Regular configuration was loaded correctly by `NVIDIAInfo equal regular.cfg`. Please record if this test was equal or not. We want it to be equal. This means the profile was matched properly.

Now, we try to swap back to Surround:

- Change from the Regular profile to the Surround profile by running `NVIDIAInfo load surround.cfg`. That will try to swap to the Surround configuration.
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-load.log"`
- Save the current profile by running `NVIDIAInfo save surround-applied.cfg`. That will save whatever the config is now, so I can compare it against what we want it to be.
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-applied.log"`
- Test that the configuration no longer matches the Regular profile by running `NVIDIAInfo equal regular.cfg`. Please record if this test was equal or not. We want it to NOT be equal.
- Test that the Surround configuration was loaded correctly by `NVIDIAInfo equal surround.cfg`. Please record if this test was equal or not. We want it to be equal. This means the profile was matched properly.

At this point, our tests are done. Please create a zip archive containing the following files, and upload it here to this issue:
- surround.cfg
- surround-applied.cfg
- NVIDIAInfo-surround-load.log
- NVIDIAInfo-surround-applied.log
- regular.cfg
- regular-applied.cfg
- NVIDIAInfo-regular-load.log
- NVIDIAInfo-regular-applied.log

I'll go through the results, and lets see if the new code works!

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-01-29 06:54
@HS34,

I've updated NVIDIAInfo to v1.5.1: [NVIDIAInfo-v1.5.1.zip](https://github.com/terrymacdonald/DisplayMagician/files/7961968/NVIDIAInfo-v1.5.1.zip)

After you have completed testing NVIDIAInfo v1.5.1 using the instructions above, can you please both try this new version of DisplayMagician I put together as well. 

This new test version of DisplayMagician v2.2.0.112 has a lot of new functionality:

- Is now a single instance, so games will start faster and display profiles will swap quicker
- Is now multithreaded to handle processing profile changes in the background
- Display layout detection is more reliable
- Now uses a new way of turning off NVIDIA surround so it avoids crashes on some video cards
- Stores the windows taskbar location and settings and attempts to reposition it to the correct place to fix NVIDIA driver issues
- Now allows you to uninstall the DisplayMagician Desktop Background Context Menu if you don't like it.

Please test it out, and tell me if there are any bugs. NOTE: There are quite a few changes in v2.2.0.112 compared to v2.1.5.5, so you will be asked to recreate new display profiles again. Please make sure you do this so that everything will work ok.
[DisplayMagicianSetup-v2.2.0.112.zip](https://github.com/terrymacdonald/DisplayMagician/files/7962890/DisplayMagicianSetup-v2.2.0.112.zip)

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-02-04 09:10
@HS34 - please ignore the last instructions I told you. Testing has moved on, and I need you to test DisplayMagician-v2.2.0.179 attached to this issue instead. It has many more features and should (hopefully) fix your problem. Please reply back to this issue telling me whether it worked or not.

IMPORTANT: You will need to delete your old DisplayProfiles_2.2.json file in c:\Users\<username>\AppData\Local\DisplayMagician\Profiles as this version has a new profile format that provides a few more features. Have a look at the 'Profile Tools' button for a new taskbar location feature!

[DisplayMagicianSetup-v2.2.0.179.zip](https://github.com/terrymacdonald/DisplayMagician/files/8001460/DisplayMagicianSetup-v2.2.0.179.zip)

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-02-06 01:12
@HS34 I fixed yet more issues, so now please test DisplayMagician v2.2.0.223 (attached)

![image](https://user-images.githubusercontent.com/5721772/152664225-ebb30318-e255-40d4-8460-1c968acaa59b.png)

Can I please trouble you to do some testing for me again? I *think* I have fixed the issues you mentioned , but I really need confirmation from you that it is now working.

IMPORTANT: Just to be sure, can you delete all your C:\Users<username>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_*.json files just so we know that all the configs are generated in the right config format? This will let me make sure it is working in a known state and avoid some of the past bugs.

Then please download DisplayMagician v2.2.0.223 and install it. Then set up new Display Profiles, and then use those profiles in the Game Shortcuts. 
[DisplayMagicianSetup-v2.2.0.223.zip](https://github.com/terrymacdonald/DisplayMagician/files/8009215/DisplayMagicianSetup-v2.2.0.223.zip)
 
Please test the following:
- Test changing between surround and non-surround profiles
- Please test changing taskbar position (can do that using the new 'Profile Tools' button under Profiles.
- Please check the UI shows the correct display layout and that the taskbar layout in the UI matches the real thing.

And then please report back with what you've found.

Thanks
Terry

**Comment by HS34** [comment] 2022-02-09 22:05
Hi Terry,
Great news : it works ! Great job ! Thank you !
There are still some bugs, but it works : I can switch to and from surround !

Here what I've tested : 
Switch from "4 screens" to "surround" : OK. Taskbar position ok.
Switch from "surround" to "4 screens": OK. Taskbar position is wrong (middle instead of right). In nVidia Configuration panel : SLI configuration is restaured to "Desactivate SLI" instead of "Activate all screens".
![Saved profile](https://user-images.githubusercontent.com/24624829/153296636-476628e8-90d9-4db4-a985-fa085052d85d.jpg)
![Restaured profile](https://user-images.githubusercontent.com/24624829/153296612-e5bc2cbe-a18c-46d2-80de-29ebe9f1b010.jpg)

Switch from "1 screen SLI optimised" to "surround" : OK. Taskbar position ok on right screen bottom.
Switch from "surround" to "1 screen SLI optimised"  : OK
Switch from "1 screen SLI optimised" to "4 screens" : Nothing happens
Switch from "1 screen SLI optimised" to  "surround" : OK. Taskbar position ok  on right screen bottom.
Switch from "surround" to "4 screens"  : failed. 3 screens activated, but not the tv. Taskbar on left screen instead of right.
Switch from "3 screens" to "4 screens" : Nothing happens
Switch from "3 screens" to "surround" : OK. Taskbar position ok.
Switch from "surround" to "4 screens"  : failed. 3 screens activated, but not the tv. Taskbar on left screen instead of right.
Switch from "3 screens" to "4 screens" : Nothing happens

Logs attached : 
[Logs.zip](https://github.com/terrymacdonald/DisplayMagician/files/8036460/Logs.zip)

The taskbar layout in the UI is wrong. It shows the taskbar on all screens. It should be only on the right one.
![DisplayMagician taskbar](https://user-images.githubusercontent.com/24624829/153297962-16a387fa-e034-4b00-99e9-c7ffe413b366.jpg)

**Comment by terrymacdonald** [comment] 2022-02-09 22:14
Hi @HS34,

Did you recreate your display profiles before you did the testing? THere
are some changes in the way that the display profiles are generated that
may cause some of the bugs. Can you please delete all your display profiles
and recreate them and then try again? Also please generate a support zip
file after you've finished testing.

I'm also trying to troubleshoot another issue with the taskbar being
applied in Windows 10 (win11 seems to work) which may be having an effect

Thanks

*Terry*

**Comment by terrymacdonald** [comment] 2022-02-10 00:02
Hi @HS34,

Can you please generate a new support ZIP file and attach it here? I need
to see what taskbar errors you're getting with 2.2.0.223 so I an figure out
the fixes.

Thanks

*Terry*

**Comment by HS34** [comment] 2022-02-10 08:08
Hi Terry,
switch from "4 screens" to "surround" : OK
switch from "surround" to "4 screens" : Taskbar restaured on left screen instead of right. TV not reactivated
![TV not reactivated](https://user-images.githubusercontent.com/24624829/153364263-51d4ff30-1ebb-4a59-a206-9f5ec3ff3c3f.jpg)
[DisplayMagician-Support-20220210-0902.zip](https://github.com/terrymacdonald/DisplayMagician/files/8039193/DisplayMagician-Support-20220210-0902.zip)

**Comment by terrymacdonald** [comment] 2022-02-17 18:35
Just letting you know I've rewritten a lot of the taskbar manipulation code as it just isn't working right by using the registry key method that the internet days I should be using. So I've started driving in deep into windows, looking at how it passes communication between windows components using windows messages to see if I can detect windows taskbar changes, and also if I can force the taskbar to certain locations through windows messages as well.

It's really complicated, and I need to learn a whole new set of skills, do it may take a bit of time until I have something for you to test.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-03-24 09:04
@HS34 Can you please help?

I've been working the last month to add in the GetDisplayConfig and SetDisplayConfig support into the NVIDIALibrary, which grabs a lot more NVIDIA settings than I used to get. But I need people with unique hardware to test things for me. You have two NVIDIA cards, and I need to test that the new NVIDIALibrary updates I made will get your hardware working properly.

I need you to test NVIDIAInfo, a little app that I wrote specifically to test the NVIDIALibrary that I wrote. Because I want to only test the video manipulation works with multiple video cards, we will only use that for testing this. Once we can confirm that it all works then I'll roll it into DisplayMagician.

Can you please download and extract this NVIDIAInfo zip file to a folder on your computer:
[NVIDIAInfo-v1.7.0.zip](https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.0)
 
Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create a surround display layout with some of your screens then:
- Save the first config as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `NVIDIAInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next create a third windows display layout, this time with a cloned display in it:
- Save the second windows display as `NVIDIAInfo save cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-save.log"`
- Check if the third windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to NOT be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `NVIDIAInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Next swap back to the cloned screen display layout again:
- Load the second windows display as `NVIDIAInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save cloned-reload.cfg`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- triple.cfg
- triple-reload.cfg
- NVIDIAInfo-triple-save.log
- NVIDIAInfo-triple-reload.log
- cloned.cfg
- cloned-reload.cfg
- NVIDIAInfo-cloned-save.log
- NVIDIAInfo-cloned-reload.log

This will give me all the information I need to know whether it worked! I need to have some confirmation from people with complex hardware so that I can be sure that it will work when the new version of NVIDIALibrary is integrated back into DisplayMagician. 

I really hope it works as this has been a TON of work :)

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-09 22:00
Hi @sven25,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-11 20:19
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-14 09:33
@HS34 New build time! I *think* I've fixed the issues you've experienced. 

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts. 

[DisplayMagicianSetup-v2.3.0.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8488041/DisplayMagicianSetup-v2.3.0.50.zip)

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a  Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by terrymacdonald** [comment] 2022-04-15 07:03
@HS34 I think this version will work for you. Can you please install this version instead of the one I suggested in previous comments and test that the problem is fixed, and then report back here.
[DisplayMagicianSetup-v2.3.1.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/8494408/DisplayMagicianSetup-v2.3.1.7.zip)

If the issue is fixed then please also close this issue so I can keep track of when I can release this new version to the general population.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-16 06:03
Another build with a couple of additional fixes that other users have reported.

The exception error when showing/saving a new profile should be fixed now. As should the detecting of the main game shutting down. You can test the new version works by downloading DisplayMagician v2.1.3.12 from here:
[DisplayMagicianSetup-v2.3.1.12.zip](https://github.com/terrymacdonald/DisplayMagician/files/8499351/DisplayMagicianSetup-v2.3.1.12.zip)

There is only one more small bug that I'm aware of that I'm trying to fix but it only seems to happen with some specific start programs and only when run from a desktop shortcut. Hoping to fix that within the next few days.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-20 08:33
@HS34 am I able to close this issue then if your last experiments show that switching Surround off now works? If it has worked then I will close this issue.

**Closed** 2022-04-20 08:33 UTC
Labels: bug
