### ISSUE TITLE
Game Shortcuts not working

### ISSUE THREAD

**Issue by sven25** [terrymacdonald/DisplayMagician#87] opened 2022-02-07 11:25 UTC
**Describe the bug**
Display Profiles are not changing via Game Shortcuts

**To Reproduce**
 -
 
**Expected behaviour**
I saw the feature for changing the audio-device with specific Game-Shortcuts, then i saw that there is an option for "Dont start a game". And i thought "Nice, thats exactly what i want". So i just want to change the default audio-device with switching Displays 
between my Desk and my Sim-Rig. But when i choose the Shortcut for my Sim-Rig, nothing happens, the Displays on the Desk 
are staying on and all Displays on the Sim-Rig are staying off.

**Screenshots**
 -

**Reporting Logs**
See attached Support Zip-File

**Enviroment (please complete the following information):**
 - Windows Version: Windows 11 (21H2, Build 22000.469)
 - DisplayMagician Version: 2.2.0.223 
 - Video Card: RTX3080Ti & StarTech USB/Dual-HDMI-Adaptor (USB32HD2)
 - Number and make/model of monitors: 1x BenQ Zowie XL2546K ; 1x NEC EA243WM (Desk)
   3x BenQ EX2780Q ; 1x BenQ RL2755HM (Racing-Rig)
 - Date of last video driver update: - 
 - Date of last windows update: - 

**Additional context**
- BenQ Zowie XL2546K connected via HDMI to the RTX3080Ti (Desk, primary Display)
- NEC EA243WM connected via HDMI to the StarTech USB/Dual-HDMI-Adaptor (Desk)
- 3x BenQ EX2780Q connected via DisplayPort to the RTX3080Ti (Sim-Rig, Triple Screen, no Surround)
- 1x BenQ RL2755HM connected via HDMI to the StarTech USB/Dual-HDMI-Adaptor (Sim-Rig, secondary Display)
- Current Nvidia Driver (511.65) is installed, the Driver for the StarTech USB/Dual-HDMI-Adaptor is also fine.

[DisplayMagician-Support-20220207-1150.zip](https://github.com/terrymacdonald/DisplayMagician/files/8014762/DisplayMagician-Support-20220207-1150.zip)

**Comment by terrymacdonald** [comment] 2022-03-06 10:15
Sorry @sven25 , I've been deep in the internals of Windows trying to set windows taskbar locations using windows internal messages for the last 4 weeks. It's not worked as I want to, so I'm coming back to going through the existing bugs I have in order to add them to the next version of DisplayMagician. I should be able to review your logs properly in the next two weeks or so. 

Just wanted to keep you updated.

Thanks
Terry

**Comment by sven25** [comment] 2022-03-06 11:27
No problem @terrymacdonald 
Thank you for the update!

**Comment by terrymacdonald** [comment] 2022-03-24 09:07
@sven25 Can you please help?

I've been working the last month to add in the GetDisplayConfig and SetDisplayConfig support into the NVIDIALibrary, which grabs a lot more NVIDIA settings than I used to get. But I need people with unique hardware to test things for me. You have unusual hardware, and I need you to test that the new NVIDIALibrary updates I made will work with your hardware properly.

I need you to test NVIDIAInfo, a little app that I wrote specifically to test the NVIDIALibrary that I wrote. Because I want to only test the video manipulation works with multiple video cards, we will only use that for testing this. Once we can confirm that it all works then I'll roll it into DisplayMagician.

Can you please download and extract this NVIDIAInfo zip file to a folder on your computer:
[NVIDIAInfo-v1.7.0.zip](https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.0)
 
Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create a surround display layout with some of your screens then:
- Save the first config as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `NVIDIAInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next create a third windows display layout, this time with a cloned display in it:
- Save the second windows display as `NVIDIAInfo save cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-save.log"`
- Check if the third windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to NOT be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `NVIDIAInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Next swap back to the cloned screen display layout again:
- Load the second windows display as `NVIDIAInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save cloned-reload.cfg`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- triple.cfg
- triple-reload.cfg
- NVIDIAInfo-triple-save.log
- NVIDIAInfo-triple-reload.log
- cloned.cfg
- cloned-reload.cfg
- NVIDIAInfo-cloned-save.log
- NVIDIAInfo-cloned-reload.log

This will give me all the information I need to know whether it worked! I need to have some confirmation from people with complex hardware so that I can be sure that it will work when the new version of NVIDIALibrary is integrated back into DisplayMagician. 

I really hope it works as this has been a TON of work :)

Thanks
Terry

**Comment by sven25** [comment] 2022-03-25 21:12
Hi Terry,
wow, it first looked kinda hard to do that, but there you go, the file is attached.
I really hope we can fix my problem with this and we can develop DisplayMagician with instructions like that.

Thanks and best regards
Sven
[NVIDIAInfo files.zip](https://github.com/terrymacdonald/DisplayMagician/files/8353816/NVIDIAInfo.files.zip)

**Comment by terrymacdonald** [comment] 2022-03-25 22:23
Yeah, I know there was a lot of steps to do, but it really is important for
me to figure out where the problem lies. It's worth help from people like
you that makes DisplayMagician better. So thank you!

Thanks
Terry

**Comment by sven25** [comment] 2022-03-26 15:36
So i assume now just a bit of patience while you develop everything? :-)

**Comment by terrymacdonald** [comment] 2022-03-26 18:09
I need to find some time to get through your logs and find any issues. I'm
currently trying to fix a memory leak with the new NVIDIA GetDisplayConfig
functionality in adding, and troubleshooting some issues with some
processes not being stopped after a game closes.

I also develop this in my spare time  for a bit of fun. I unfortunately
don't have as much spare time as I once did, which means the amount of time
I can spend is more limited than it once was.

All of that combined means yes, you'll need a bit of patience until I can
get all the bugs found and removed. It's also really important to make sure
that any new code is thoroughly tested before it's released, which is part
of the reason this is all taking so long.

Thanks
Terry

**Comment by sven25** [comment] 2022-03-26 20:04
All fine Terry, i don't want to argue with you, please don't get me wrong there.

I like it very much when developers are in touch with the users to develope their programs.

Keep up the great work!

**Comment by terrymacdonald** [comment] 2022-03-26 20:27
Hi @Sven25,

Oh sorry, I didn't mean it that way if that's what it seemed. I was just
highlighting some of the reasons I haven't been as responsive as I normally
am. I'm really wanting to make sure this is the last time that users will
need to recreate their display profiles, so I'm trying to make sure the
NVIDIALibrary and WinLibrary are both as reliable as possible, and cope
with the huge range of hardware out there.

With these latest changes NVIDIALibrary is designed to handle multiple
physical adapters in a logical group, dvi-d and earlier connections, USB
connected displays, adaptive sync, image scaling, cloned displays and more.
It's a lot of things to test and get reliable. And that unfortunately takes
time.

I'm really hoping that the next release is the final big one for a while,
as I need to start working on DisplayMagician V3.0 soon. That version will
move to .Net V6 and will use a MAUI interface, and will add unit testing
and multi language. It's a major change, so I want to make sure that I've
added all the functionality into DisplayMagician v2.3 first.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-09 21:56
Hi @sven25,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-11 20:18
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-14 09:32
@sven25 New build time! I *think* I've fixed the issues you've experienced. 

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts. 

[DisplayMagicianSetup-v2.3.0.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8488041/DisplayMagicianSetup-v2.3.0.50.zip)

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a  Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by terrymacdonald** [comment] 2022-04-15 07:02
I think this version will work for you. Can you please install this version instead of the one I suggested in previous comments and test that the problem is fixed, and then report back here.
[DisplayMagicianSetup-v2.3.1.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/8494408/DisplayMagicianSetup-v2.3.1.7.zip)

If the issue is fixed then please also close this issue so I can keep track of when I can release this new version to the general population.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-19 10:26
@sven25  I have worked through many issues over the last week, so I recommend that you do some testing with this version:
[DisplayMagicianSetup-v2.3.1.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8512144/DisplayMagicianSetup-v2.3.1.50.zip)

I **strongly** recommend that  you delete your old display profiles and recreate them again just to be 100% sure you're running the latest versions of the file, and then updated your game shortcuts to use those new profiles.

This version fixes all the bugs that I know about, and based on my testing is just about ready to release to the general public. I'd really appreciate it if you could do some testing (but only if you have some spare time) so that I will know if it really does fix all the issues.

Thanks
Terry

**Comment by terrymacdonald** [comment] 2022-04-20 20:40
@sven25 I've just released a new version of DisplayMagician that should fix the issue you're experiencing. Please download DisplayMagician v2.3.1.60 from [https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.3.1](https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.3.1) and see how things go.

I will close this issue for now, but if you have exactly the same issue then please reopen this case. If you have a brand new issue that is different, then please log a [new issue](https://github.com/terrymacdonald/DisplayMagician/issues/new/choose).

Thanks
Terry

**Closed by terrymacdonald** 2022-04-20 20:40 UTC
Labels: bug

**Comment by sven25** [comment] 2022-06-29 11:53
Hi Terry,
sorry for answering that late.
First of all thank you very much for the effort in developing this nice tool.
With version 2.3.1.60 the Game Shortcuts are generally working now, which is great!

So now there is a little thing with the audio setting:

- Game Shortcut 1 sets the default microphone to lets say "mic 1"
- Game Shortcut 2 sets the default microphone to "mic 2"
